version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  enable:
    - errorlint
    - errcheck
    - goconst
    - gosec
    - unconvert
    - depguard
    - exhaustive
    - govet
    - makezero
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - whitespace
  settings:
    errorlint:
      errorf: true
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    goconst:
      min-len: 3
      min-occurrences: 3
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by go.uber.org/zap
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      enable:
        - atomicalign
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    makezero:
      always: false
    misspell:
      locale: US
      ignore-rules:
        - someword
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: internal/hmac/
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: 'SA9003:'
        source: '^//go:generate '
      - path: (.+)\.go$
        text: declaration of "(err|ctx|logger)" shadows declaration at
    paths:
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/ssvlabs/ssv/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
