version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  enable:
    - errorlint
    - goconst
    - gosec
    - unconvert
  settings:
    cyclop:
      max-complexity: 10
      package-average: 0
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by go.uber.org/zap
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    exhaustruct:
      exclude:
        - .*.Test
        - .*.Test2
        - .*.Embedded
        - .*.External
    forbidigo:
      forbid:
        - pattern: fmt.Errorf
        - pattern: fmt.Print.*
        - pattern: ginkgo\\.F.*
      exclude-godoc-examples: false
    funlen:
      lines: 60
      statements: 40
    gocognit:
      min-complexity: 10
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-checks:
        - rangeValCopy
      disabled-checks:
        - regexpMust
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        ruleguard:
          rules: ""
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 120
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
      ignore-rules:
        - someword
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    testpackage:
      skip-regexp: (export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: internal/hmac/
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        source: '^//go:generate '
      - path: (.+)\.go$
        text: declaration of "(err|ctx|logger)" shadows declaration at
    paths:
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: true
formatters:
  settings:
    gci:
      sections:
        - prefix(github.com/ssvlabs/ssv)
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false
    goimports:
      local-prefixes:
        - github.com/ssvlabs/ssv
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
