coverage:
  range: 60..100
  round: down
  precision: 1
  status:
    project:
      default:
        # Avoid false negatives
        threshold: 1%

comment:
  behavior: default
  layout: "condensed_header, condensed_files, condensed_footer" # add "condensed_" to "header", "files" and "footer"
  hide_project_coverage: false # set to true
  require_changes: true  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]


codecov:
  require_ci_to_pass: false
# ref: https://docs.codecov.com/docs/codecovyml-reference

ignore:
  - "protocol"
  - "protocol/v2/blockchain/beacon/mocks"
  - "protocol/v2/blockchain/beacon/mock_validator_metadata.go"
  - "integration"
  - "docs"
  - "eth/contract"
  - "eth/simcontract"
  - "scripts"
  - "operator/duties/mocks"
  - "operator/fee_recipient/mocks"
  - "operator/slotticker/mocks"
  - "operator/validator/mocks"
  - "network/streams/metrics.go"
  - "network/discovery/metrics.go"
  - "network/p2p/metrics.go"
  - "network/peers/metrics.go"
  - "network/peers/connections/metrics.go"
  - "network/peers/connections/mock/mock_storage.go"
  - "network/topics/metrics.go"
  - "protocol/v2/ssv/validator/metrics.go"
  - "protocol/v2/ssv/runner/metrics/metrics.go"
  - "protocol/v2/ssv/queue/metrics.go"
  - "protocol/v2/qbft/instance/metrics.go"
  - "exporter/api/metrics.go"
  - "eth/executionclient/metrics.go"
  - "eth/eventsyncer/metrics.go"
  - "eth/eventsyncer/event_syncer_mock.go"
  - "eth/eventhandler/metrics.go"
  - "operator/validator/metrics.go"
  - "operator/metrics.go"
  - "protocol/v2/qbft/controller/types.go"
  - "api/types.go"
  - "beacon/goclient/types.go"
  - "cli/operator/generate_doc.go"
  - "migrations/migration_0_example.go"
  - "migrations/migration_1_example.go"
  - "registry/storage/mocks"
