apiVersion: v1
kind: Pod
metadata:
  name: tcpproxy-pod
  namespace: ssv
  labels:
    app: tcpproxy-pod
spec:
  containers:
    - name: sleep-container
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      ports:
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
        - containerPort: 8004
        - containerPort: 8005
        - containerPort: 8006
        - containerPort: 8007
        - containerPort: 8008
        - containerPort: 8009
        - containerPort: 8010
  restartPolicy: Never
