---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-exporter-2
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "ws-exporter-2.{{ .Values.domain }}"
  gateways:
  - ssv-exporter-2
  http:
  - route:
    - destination:
        host: ssv-exporter-2
        port:
          number: 14007
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-exporter-2
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ws-exporter-2.{{ .Values.domain }}"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-exporter-2
  namespace: {{ .Values.namespace }}
  labels:
    app: ssv-exporter-2
spec:
  type: ClusterIP
  ports:
    - port: 12007
      protocol: UDP
      targetPort: 12007
      name: port-12007
    - port: 13007
      protocol: TCP
      targetPort: 13007
      name: port-13007
    - port: 14007
      protocol: TCP
      targetPort: 14007
      name: port-14007
    - port: 15007
      protocol: TCP
      targetPort: 15007
      name: port-15007
  selector:
    app: ssv-exporter-2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: ssv-exporter-2
  name: ssv-exporter-2
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.ssv_exporter_2 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-exporter-2
  template:
    metadata:
      labels:
        app: ssv-exporter-2
    spec:
      containers:
      - name: ssv-exporter-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu:  {{ .Values.resources.limits_exporter_2.cpu }}
            memory: {{ .Values.resources.limits_exporter_2.mem }}
        command: ["make", "start-node"]
        ports:
        - containerPort: 12007
          name: port-12007
          hostPort: 12007           
          protocol: UDP
        - containerPort: 13007
          name: port-13007
          hostPort: 13007
        - containerPort: 14007
          name: port-14007
          hostPort: 14007
        - containerPort: 15007
          name: port-15007
          hostPort: 15007
        env:
          - name: SHARE_CONFIG
            value: "./data/share.yaml"
          - name: CONFIG_PATH
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: config_path
          - name: BOOTNODES
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node
          - name: REGISTRY_CONTRACT_ADDR_KEY
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: smart_contract_addr_key
          - name: ETH_1_SYNC_OFFSET
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: eth_1_sync_offset
                optional: true
          - name: ABI_VERSION
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: abi_version
                optional: true
          - name: LOG_LEVEL
            value: "debug"
          - name: DEBUG_SERVICES
            value: "ssv.*"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "prater"
          - name: DB_PATH
            value: "./data/db-v3-shifu"
          - name: NETWORK_ID
            value: "0x00003011"
          - name: DB_REPORTING
            value: "false"
          - name: METRICS_API_PORT
            value: "15007"
          - name: ENABLE_PROFILE
            value: "true"
          - name: GENERATE_OPERATOR_KEY
            value: "true"
          - name: UDP_PORT
            value: "12007"
          - name: TCP_PORT
            value: "13007"
          - name: WS_API_PORT
            value: "14007"
          - name: FULLNODE
            value: "true"
          - name: EXPORTER
            value: "true"
          - name: GENESIS_EPOCH
            value: "1"
          - name: DISCOVERY_TRACE
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: SUBNETS
            value: "0xffffffffffffffffffffffffffffffff"
        volumeMounts:
        - mountPath: /data
          name: ssv-exporter-v2
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-exporter-2-cm
      volumes:
      - name: ssv-exporter-v2
        persistentVolumeClaim:
          claimName: ssv-exporter-v2
      - name: ssv-exporter-2-cm
        configMap:
          name: ssv-exporter-2-cm
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
