{
 "title": "SSV Validator (Stage)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4"
   },
   {
    "name": "pubkey",
    "label": "Public Key",
    "query": {
     "query": "ssv_p2p_connected_peers{instance=~\"$instance.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:status{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_p2p_connected_peers{instance=~\"$instance.*\",pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  { "title": "Attestation Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Full Flow",
   "type": "timeseries",
   "description": "Attestation full flow duration excluding waiting for 1/3 of slot time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_attestation_full_flow_duration_seconds_bucket{instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "description": "Duration from proposal to commits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_consensus_duration_seconds_bucket{instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proposal Stage",
   "type": "timeseries",
   "description": "Proposal stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prepare Stage",
   "type": "timeseries",
   "description": "Prepare stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Commit Stage",
   "type": "timeseries",
   "description": "Commit stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Signature Collection",
   "type": "timeseries",
   "description": "Attestation signature collection stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_post_consensus_duration_seconds_bucket{instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Attestation Submission",
   "type": "timeseries",
   "description": "Attestation submission duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_attestation_submission_duration_seconds_bucket{instance=~\"$instance.*\",pubKey=\"$pubkey\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Decided Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Decided Messages (Node 1)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{instance=~\"$instance.*\",pubKey=\"$pubkey\",nodeId=\"1\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 2)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 41 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{instance=~\"$instance.*\",pubKey=\"$pubkey\",nodeId=\"2\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 3)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{instance=~\"$instance.*\",pubKey=\"$pubkey\",nodeId=\"3\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 4)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{instance=~\"$instance.*\",pubKey=\"$pubkey\",nodeId=\"4\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Incoming Decided Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "ssv:network:net_messages_inbound{instance=~\"$instance.*\",pubKey=\"$pubkey\",type=\"DecidedType\"}",
     "legendFormat": "Node {{signer}}"
    }
   ]
  },
  { "title": "IBFT Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Outgoing IBFT Messages",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "ssv:network:ibft_messages_outbound{instance=~\"$instance.*\",pubKey=\"$pubkey\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Incoming IBFT Messages",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 7, "y": 58 },
   "targets": [
    {
     "expr": "ssv:network:ibft_messages_inbound{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Incoming IBFT Messages Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "ssv:network:net_messages_inbound{instance=~\"$instance.*\",pubKey=\"$pubkey\",type=\"IBFTType\"}",
     "legendFormat": "Node {{signer}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Highest Decided",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_highest_decided{instance=~\"$instance.*\",pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "IBFT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:running_ibfts_count{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Stage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Sequence",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_sequence{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_slot{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_round{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  }
 ]
}