{
 "title": "SSV Operator Node",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ssv:node_status, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ssv:node_status{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(ssv:node_status{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   },
   { "name": "validator_dashboard_id", "query": "${VAR_VALIDATOR_DASHBOARD_ID}" },
   {
    "name": "persistentvolumeclaim",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Validators Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators (Attestation)",
   "type": "table",
   "description": "Information on attestation duties for all validators registered to an operator",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_highest_decided{namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:network:connected_peers{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_sequence{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_round{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:running_ibfts_count{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_slot{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "ssv:validator:status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:beacon:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv:eth1:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "ssv:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}",
     "legendFormat": "SSV Operator"
    }
   ]
  },
  {
   "title": "Operator Node Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ssv:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Status of the connected ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "ssv:eth1:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Status of the connected beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "ssv:beacon:node_status{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=~\"$pod.*\"}"
    }
   ]
  },
  { "title": "Process Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$persistentvolumeclaim\"}",
     "legendFormat": "{{persistentvolumeclaim}}-used"
    },
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$persistentvolumeclaim\"})-(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$persistentvolumeclaim\"})",
     "legendFormat": "{{persistentvolumeclaim}}-free"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$persistentvolumeclaim\"}",
     "legendFormat": "{{persistentvolumeclaim}}-total"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", namespace=~\"$namespace.*\", pod=\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}