{
 "title": "SSV Validator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ssv:node_status, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ssv:node_status, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(ssv:node_status{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pubkey",
    "label": "Public Key",
    "query": {
     "query": "ssv:network:connected_peers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:status{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:network:connected_peers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  { "title": "Decided Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Decided Messages (Node 1)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", nodeId=\"1\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 2)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", nodeId=\"2\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 3)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", nodeId=\"3\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Decided Messages (Node 4)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_decided_signers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", nodeId=\"4\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Incoming Decided Messages Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ssv:network:net_messages_inbound{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", type=\"DecidedType\"}",
     "legendFormat": "Node {{signer}}"
    }
   ]
  },
  { "title": "IBFT Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Outgoing IBFT Messages",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ssv:network:ibft_messages_outbound{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}",
     "legendFormat": "{{seq}}"
    }
   ]
  },
  {
   "title": "Incoming IBFT Messages",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "ssv:network:ibft_messages_inbound{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Incoming IBFT Messages Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ssv:network:net_messages_inbound{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\", type=\"IBFTType\"}",
     "legendFormat": "Node {{signer}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Highest Decided",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_highest_decided{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "IBFT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:running_ibfts_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Stage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Sequence",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_sequence{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_slot{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_round{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", pubKey=\"$pubkey\"}"
    }
   ]
  }
 ]
}