{
 "title": "SSV Operator Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4,ssv-node-v2-5,ssv-node-v2-6,ssv-node-v2-7,ssv-node-v2-8,ssv-node-9,ssv-node-10,ssv-node-11,ssv-node-12,ssv-exporter,ssv-exporter-v2"
   },
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   },
   { "name": "validator_dashboard_id", "query": "${VAR_VALIDATOR_DASHBOARD_ID}" }
  ]
 },
 "panels": [
  { "title": "Network Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subnets Peers Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ssv:network:subnets:known{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:connected{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:my{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Total Connections Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "ssv:network:all_connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Peers Discovery Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(ssv:network:discovery:found{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Found"
    },
    {
     "expr": "rate(ssv:network:discovery:rejected{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "DiscV5 Ping/Pong",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "ssv:network:discovery:enr_ping{instance=~\"$instance.*\"}",
     "legendFormat": "Ping"
    },
    {
     "expr": "ssv:network:discovery:enr_pong{instance=~\"$instance.*\"}",
     "legendFormat": "Pong"
    }
   ]
  },
  {
   "title": "Topics Peers Distribution ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ssv:network:connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  { "title": "Network Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Network I/O (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "in {{pod}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "out {{pod}}"
    }
   ]
  },
  {
   "title": "Pubsub Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Incoming Topic Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Topic Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Pubsub Trace distribution (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(ssv:network:pubsub:trace{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Stream Protocols",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 60 },
   "targets": [
    {
     "expr": "ssv:p2p:streams:res{instance=~\"$instance.*\"}",
     "legendFormat": "Responses"
    },
    {
     "expr": "ssv:p2p:streams:req:count{instance=~\"$instance.*\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:success{instance=~\"$instance.*\"}",
     "legendFormat": "Successful Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:active{instance=~\"$instance.*\"}",
     "legendFormat": "Active"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "count(ssv:validator:status{instance=~\"$instance.*\"} == 3)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ssv:validator:status{instance=~\"$instance.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Change Round Distribution ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv:validator:ibft_stage{instance=~\"$instance.*\"} == 4)",
     "legendFormat": "All Change Round"
    },
    {
     "expr": "count(ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
     "legendFormat": "Total Above Round 2"
    },
    {
     "expr": "count_values(\"round\", ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Change Round",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 71 },
   "targets": [
    {
     "expr": "count(ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
     "legendFormat": "All Change Round"
    }
   ]
  },
  {
   "title": "Validators (Attestation)",
   "type": "table",
   "description": "Information on attestation duties for all validators registered to an operator",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_highest_decided{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:connected_peers{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_sequence{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_round{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:running_ibfts_count{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:ibft_current_slot{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:validator:status{instance=~\"$instance.*\"}"
    }
   ]
  },
  { "title": "QBFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Processed Messages by Workers (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "rate (ssv:worker:msg:process{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Processed Messages Rate"
    }
   ]
  },
  {
   "title": "QBFT Message Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 95 },
   "targets": [
    {
     "expr": "sum by (v) (ssv:ibft:msgq:ratio{instance=~\"$instance.*\"})",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "QBFT Message Queue Size",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "ssv:ibft:msgq:ratio{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "QBFT Message Queue Size (Types)",
   "type": "table",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "ssv:ibft:msgq:ratio{instance=~\"$instance.*\"}"
    }
   ]
  },
  { "title": "Operators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Version Distribution",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "ssv:network:peers_identity{instance=~\"ssv-exporter.*\"}"
    }
   ]
  },
  {
   "title": "Known Operators",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "ssv:network:peers_identity{instance=~\"$instance.*\"}"
    },
    { "expr": "ssv:exporter:operator_index{}" }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 153 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:beacon:node_status{instance=~\"$instance.*\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv:eth1:node_status{instance=~\"$instance.*\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "ssv:node_status{instance=~\"$instance.*\"}",
     "legendFormat": "SSV Operator"
    },
    {}
   ]
  },
  {
   "title": "Operator Node Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ssv:node_status{instance=~\"$instance.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Status of the connected ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 153 },
   "targets": [
    {
     "expr": "ssv:eth1:node_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Status of the connected beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 153 },
   "targets": [
    {
     "expr": "ssv:beacon:node_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  { "title": "Process Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "Memory (Go)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "stack_inuse_bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage (k8s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$instance.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network I/O (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "in {{pod}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "out {{pod}}"
    }
   ]
  }
 ]
}