{
 "title": "Operator Performance Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4,ssv-node-v2-5,ssv-node-v2-6,ssv-node-v2-7,ssv-node-v2-8,ssv-node-9,ssv-node-10,ssv-node-11,ssv-node-12,ssv-exporter,ssv-exporter-v2,ssv-node-v3-1,ssv-node-v3-2,ssv-node-v3-3,ssv-node-v3-4"
   }
  ]
 },
 "panels": [
  { "title": "Operator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "description": "Total amount of validators and total active validators\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 3)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Attester Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"} > 1)",
     "legendFormat": "round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"} > 2)",
     "legendFormat": "round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"})",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"ATTESTER\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"ATTESTER\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow (Excl. Att. Data Req.) Duration",
   "type": "timeseries",
   "description": "Attestation full flow duration excluding waiting for 1/3 of slot time and attestation data request.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Proposal Stage Duration",
   "type": "timeseries",
   "description": "Proposal stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Prepare Stage Duration",
   "type": "timeseries",
   "description": "Prepare stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Commit Stage Duration",
   "type": "timeseries",
   "description": "Commit stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for an attester role (duration from proposal to commits) broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Post-consensus (signature collection) Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for an attester role (signature collection duration) broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Attestation Data Request Duration",
   "type": "timeseries",
   "description": "Attestation data request duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_beacon_attestation_data_request_duration_seconds_bucket{le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_beacon_attestation_data_request_duration_seconds_count{instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Attestation Submission Duration",
   "type": "timeseries",
   "description": "Attestation submission duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Proposer Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"} > 1)",
     "legendFormat": "round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"} > 2)",
     "legendFormat": "round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"})",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"PROPOSER\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"PROPOSER\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Block Submission Duration",
   "type": "timeseries",
   "description": "Block submission duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Aggregator Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"} > 1)",
     "legendFormat": "round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"} > 2)",
     "legendFormat": "round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"})",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"AGGREGATOR\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"AGGREGATOR\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Proof Submission Duration",
   "type": "timeseries",
   "description": "Proof submission duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Sync Committee Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"} > 1)",
     "legendFormat": "round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"} > 2)",
     "legendFormat": "round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"})",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 105 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Sync Message Submission Duration",
   "type": "timeseries",
   "description": "Sync Message submission duration for a sync committee role. Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Sync Committee Aggregator Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"} > 1)",
     "legendFormat": "round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"} > 2)",
     "legendFormat": "round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"})",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 131 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE_CONTRIBUTION\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 2 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 131 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE_CONTRIBUTION\"}[2m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a sync committee aggregator role. Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Signed Contribution And Proof Submission Duration",
   "type": "timeseries",
   "description": "Signed contribution and proof submission duration for a sync committee aggregator role. Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"2.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"3.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"2.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "2 - 3 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"4.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"3.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "3 - 4 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"10.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"4.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "4 - 10 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"10.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 10 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[2m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[2m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[2m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  }
 ]
}