{
 "title": "Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4,ssv-node-v2-5,ssv-node-v2-6,ssv-node-v2-7,ssv-node-v2-8,ssv-node-9,ssv-node-10,ssv-node-11,ssv-node-12,ssv-exporter,ssv-exporter-v2,ssv-node-v3-1,ssv-node-v3-2,ssv-node-v3-3,ssv-node-v3-4"
   },
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   }
  ]
 },
 "panels": [
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_beacon_status{instance=~\"$instance.*\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv_eth1_status{instance=~\"$instance.*\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "ssv_node_status{instance=~\"$instance.*\"}",
     "legendFormat": "SSV Operator"
    },
    {}
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Status of the connected beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ssv_beacon_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Status of the connected ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "ssv_eth1_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Operator Node Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ssv_node_status{instance=~\"$instance.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "-absent(ssv_node_status{instance=~\"$instance.*\"})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory Usage (RAM)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$instance.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (Go)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "stack_inuse_bytes"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage (HDD)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network I/O (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "in {{pod}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "out {{pod}}"
    }
   ]
  },
  { "title": "Network Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_p2p_all_connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "Subnet Peers Distribution ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 27 },
   "targets": [
    {
     "expr": "ssv_p2p_connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "Subnets Peers Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "ssv:network:subnets:known{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:connected{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:my{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Peers Discovery Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(ssv:network:discovery:found{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Found"
    },
    {
     "expr": "rate(ssv:network:discovery:rejected{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "ssv:network:peers_identity{instance=~\"$instance.*\"}"
    },
    { "expr": "ssv:exporter:operator_index{}" }
   ]
  },
  { "title": "Network Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Pubsub Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Outgoing Pubsub Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Pubsub Messages (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Stream Protocols (table)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "ssv:p2p:streams:res{instance=~\"$instance.*\"}",
     "legendFormat": "Responses"
    },
    {
     "expr": "ssv:p2p:streams:req:count{instance=~\"$instance.*\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:success{instance=~\"$instance.*\"}",
     "legendFormat": "Successful Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:active{instance=~\"$instance.*\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Stream Protocols (time-series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(ssv:p2p:streams:res{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Responses {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:count{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Requests {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:success{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Successful Requests {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:active{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "Active {{pid}}"
    }
   ]
  }
 ]
}