{
 "title": "Operator Performance Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "ssv-node-v2-1,ssv-node-v2-2,ssv-node-v2-3,ssv-node-v2-4,ssv-node-v2-5,ssv-node-v2-6,ssv-node-v2-7,ssv-node-v2-8,ssv-node-9,ssv-node-10,ssv-node-11,ssv-node-12,ssv-exporter,ssv-exporter-v2,ssv-node-v3-1,ssv-node-v3-2,ssv-node-v3-3,ssv-node-v3-4"
   }
  ]
 },
 "panels": [
  { "title": "Operator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 3)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\"} > 2)",
     "legendFormat": "Total Above Round 2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\"} > 2)",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Operator Effectiveness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "effectiveness{instance=\"http://vc.stage.bloxinfra.com/api/monitor/effectiveness/?network=prater\",job=\"json\"}",
     "legendFormat": "effectiveness",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "effectiveness{instance=\"http://vc.stage.bloxinfra.com/api/monitor/effectiveness/?network=prater&epochs_number=10\",job=\"json\"}",
     "legendFormat": "effectiveness-10"
    },
    {
     "expr": "effectiveness{instance=\"http://vc.stage.bloxinfra.com/api/monitor/effectiveness/?network=prater&epochs_number=300\",job=\"json\"}",
     "legendFormat": "effectiveness-300"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_validator_roles_submitted{instance=~\"$instance.*\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_validator_roles_failed{instance=~\"$instance.*\", pubKey=\"$pubkey\", role=\"$role\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  { "title": "Attester Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Attestation Data Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ssv_beacon_attestation_data_request_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Full Flow (Excl. Att. Data Req.)",
   "type": "timeseries",
   "description": "Attestation full flow duration excluding waiting for 1/3 of slot time and attestation data request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "description": "Duration from proposal to commits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proposal Stage",
   "type": "timeseries",
   "description": "Proposal processing ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",instance=~\"$instance.*\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prepare Stage",
   "type": "timeseries",
   "description": "Prepare stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Commit Stage",
   "type": "timeseries",
   "description": "Commit stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Post-consensus (sign. collection)",
   "type": "timeseries",
   "description": "Signature collection duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Attestation Submission",
   "type": "timeseries",
   "description": "Attestation submission duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Proposer Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Full Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "description": "Duration from proposal to commits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pre-consensus",
   "type": "timeseries",
   "description": "Pre-consensus duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Post-consensus",
   "type": "timeseries",
   "description": "Post-consensus duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Submission",
   "type": "timeseries",
   "description": "Block submission duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Aggregator Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Full Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "description": "Duration from proposal to commits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pre-consensus",
   "type": "timeseries",
   "description": "Pre-consensus duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Post-consensus",
   "type": "timeseries",
   "description": "Post-consensus duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proof Submission",
   "type": "timeseries",
   "description": "Proof submission duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum(increase(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}