package storage

import (
	"crypto/rsa"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkg/errors"
	specqbft "github.com/ssvlabs/ssv-spec/qbft"
	spectypes "github.com/ssvlabs/ssv-spec/types"
	"github.com/ssvlabs/ssv-spec/types/testingutils"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"

	"github.com/ssvlabs/ssv/ssvsigner/keys/rsaencryption"
)

var (
	specGoModEnv = "SSV_SPEC_GOMOD"
	specModule   = "github.com/ssvlabs/ssv-spec"
)

// TODO: add missing tests

// GenerateOperatorSigner generates randomly nodes
func GenerateOperatorSigner(oids ...spectypes.OperatorID) ([]*rsa.PrivateKey, []*spectypes.Operator) {
	nodes := make([]*spectypes.Operator, 0, len(oids))
	sks := make([]*rsa.PrivateKey, 0, len(oids))

	for i := range oids {
		pubKey, privKey, err := rsaencryption.GenerateKeyPairPEM()
		if err != nil {
			panic(err)
		}
		opKey, err := rsaencryption.PEMToPrivateKey(privKey)
		if err != nil {
			panic(err)
		}

		nodes = append(nodes, &spectypes.Operator{
			OperatorID:        oids[i],
			SSVOperatorPubKey: pubKey,
		})

		sks = append(sks, opKey)
	}

	return sks, nodes
}

// MsgGenerator represents a message generator
type MsgGenerator func(height specqbft.Height) ([]spectypes.OperatorID, *specqbft.Message)

// CreateMultipleStoredInstances enables to create multiple stored instances (with decided messages).
func CreateMultipleStoredInstances(
	sks []*rsa.PrivateKey,
	start specqbft.Height,
	end specqbft.Height,
	generator MsgGenerator,
) ([]*StoredInstance, error) {
	results := make([]*StoredInstance, 0)
	for i := start; i <= end; i++ {
		signers, msg := generator(i)
		if msg == nil {
			break
		}
		sm := testingutils.MultiSignQBFTMsg(sks, signers, msg)

		var qbftMsg specqbft.Message
		if err := qbftMsg.Decode(sm.SSVMessage.Data); err != nil {
			return nil, err
		}

		results = append(results, &StoredInstance{
			State: &specqbft.State{
				ID:                   qbftMsg.Identifier,
				Round:                qbftMsg.Round,
				Height:               qbftMsg.Height,
				LastPreparedRound:    qbftMsg.Round,
				LastPreparedValue:    sm.FullData,
				Decided:              true,
				DecidedValue:         sm.FullData,
				ProposeContainer:     specqbft.NewMsgContainer(),
				PrepareContainer:     specqbft.NewMsgContainer(),
				CommitContainer:      specqbft.NewMsgContainer(),
				RoundChangeContainer: specqbft.NewMsgContainer(),
			},
			DecidedMessage: sm,
		})
	}
	return results, nil
}

// SignMsg handle MultiSignMsg error and return just specqbft.SignedMessage
func SignMsg(t *testing.T, sks []*rsa.PrivateKey, signers []spectypes.OperatorID, msg *specqbft.Message) *spectypes.SignedSSVMessage {
	return testingutils.MultiSignQBFTMsg(sks, signers, msg)
}

func GenerateSpecTestJSON(path string, module string) ([]byte, error) {
	// Step 1: Get the spec directory.
	p, err := GetSpecDir(path, module)
	if err != nil {
		return nil, fmt.Errorf("could not get spec test dir: %w", err)
	}

	p = filepath.Join(p, "spectest", "generate")

	// Step 2: Create a temporary directory at /tmp/<module>.
	tmpDir := filepath.Join("/tmp", module)
	if err := os.MkdirAll(tmpDir, 0750); err != nil {
		return nil, fmt.Errorf("failed to create tmp directory: %w", err)
	}
	// Clean up the temp directory when the function exits.
	defer func() {
		err := os.RemoveAll(tmpDir)
		if err != nil {
			fmt.Printf("failed to remove tmp directory: %s", err.Error())
		}
	}()

	// Step 3: Build the Go package, outputting an executable to tmpDir.
	// We'll name the executable after the module.
	binaryPath := filepath.Join(tmpDir, module)
	//nolint: gosec
	cmdBuild := exec.Command("go", "build", "-o", binaryPath, ".")
	cmdBuild.Dir = p
	buildOutput, err := cmdBuild.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("go build failed: %w; output: %s", err, buildOutput)
	}

	// Step 4: Execute the built binary.
	// It is assumed that running the binary generates tests.json in tmpDir.
	//nolint: gosec
	cmdRun := exec.Command(binaryPath)
	cmdRun.Dir = tmpDir
	_, err = cmdRun.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("failed to run binary: %w", err)
	}

	// Step 5: Read the tests.json file generated by the binary.
	testJSONPath := filepath.Join(tmpDir, "tests.json")
	//nolint: gosec
	jsonBytes, err := os.ReadFile(testJSONPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read tests.json: %w", err)
	}

	return jsonBytes, nil
}

// GetSpecDir returns the path to the ssv-spec module.
func GetSpecDir(path, module string) (string, error) {
	if path == "" {
		var err error
		path, err = os.Getwd()
		if err != nil {
			return "", errors.New("could not get current directory")
		}
	}
	goModFile, err := getGoModFile(path)
	if err != nil {
		return "", errors.New("could not get go.mod file")
	}

	// check if there is a replace
	var modPath, modVersion string
	var replace *modfile.Replace
	for _, r := range goModFile.Replace {
		if strings.EqualFold(specModule, r.Old.Path) {
			replace = r
			break
		}
	}

	if replace != nil {
		modPath = replace.New.Path
		modVersion = replace.New.Version
	} else {
		// get from require
		var req *modfile.Require
		for _, r := range goModFile.Require {
			if strings.EqualFold(specModule, r.Mod.Path) {
				req = r
				break
			}
		}
		if req == nil {
			return "", errors.Errorf("could not find %s module", specModule)
		}
		modPath = req.Mod.Path
		modVersion = req.Mod.Version
	}

	// get module path
	p, err := GetModulePath(modPath, modVersion)
	if err != nil {
		return "", errors.Wrap(err, "could not get module path")
	}

	if _, err := os.Stat(p); os.IsNotExist(err) {
		return "", errors.Wrapf(err, "you don't have this module-%s/version-%s installed", modPath, modVersion)
	}

	return filepath.Join(filepath.Clean(p), module), nil
}

func GetModulePath(name, version string) (string, error) {
	cachePath, err := moduleCachePath(name, version)
	if err == nil {
		if _, statErr := os.Stat(cachePath); statErr == nil {
			return cachePath, nil
		}
	}

	// Resolve from the selected modfile's build list first.
	if resolvedPath, err := resolveModuleDirViaGoList(name); err == nil && strings.TrimSpace(resolvedPath) != "" {
		return resolvedPath, nil
	}

	// If the module is not present in cache yet, ask Go to download it and
	// report the extracted module dir.
	modQuery := name
	if version != "" {
		modQuery = fmt.Sprintf("%s@%s", name, version)
	}

	cmd := exec.Command("go", "mod", "download", "-json", modQuery)
	cmd.Env = envWithOptionalGoMod()
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("could not resolve module path for %s: %w; output: %s", modQuery, err, strings.TrimSpace(string(out)))
	}

	var downloaded struct {
		Dir   string `json:"Dir"`
		Error string `json:"Error"`
	}
	if err := json.Unmarshal(out, &downloaded); err != nil {
		return "", fmt.Errorf("could not resolve module path for %s: invalid go mod download output: %w; output: %s", modQuery, err, strings.TrimSpace(string(out)))
	}
	if downloaded.Error != "" {
		return "", fmt.Errorf("could not resolve module path for %s: %s", modQuery, downloaded.Error)
	}
	if strings.TrimSpace(downloaded.Dir) == "" {
		// Some Go versions may omit Dir in download output; re-check using go list.
		if resolvedPath, err := resolveModuleDirViaGoList(name); err == nil && strings.TrimSpace(resolvedPath) != "" {
			return resolvedPath, nil
		}
		if cachePath != "" {
			if _, statErr := os.Stat(cachePath); statErr == nil {
				return cachePath, nil
			}
		}
		return "", fmt.Errorf("could not resolve module path for %s: empty module dir", modQuery)
	}
	return downloaded.Dir, nil
}

func moduleCachePath(name, version string) (string, error) {
	// first we need GOMODCACHE
	cache, ok := os.LookupEnv("GOMODCACHE")
	if !ok {
		cache = path.Join(os.Getenv("GOPATH"), "pkg", "mod")
	}

	// then we need to escape path
	escapedPath, err := module.EscapePath(name)
	if err != nil {
		return "", err
	}

	// version also
	escapedVersion, err := module.EscapeVersion(version)
	if err != nil {
		return "", err
	}

	return path.Join(cache, escapedPath+"@"+escapedVersion), nil
}

func envWithOptionalGoMod() []string {
	env := os.Environ()

	modPath := strings.TrimSpace(os.Getenv(specGoModEnv))
	if modPath == "" {
		return env
	}

	if !filepath.IsAbs(modPath) {
		if wd, err := os.Getwd(); err == nil {
			if root, err := findModuleRoot(wd); err == nil {
				modPath = filepath.Join(root, modPath)
			}
		}
	}

	// Make sure go subcommands resolve modules against the same modfile used by tests.
	return append(env, "GOMOD="+modPath, "GOWORK=off")
}

func resolveModuleDirViaGoList(name string) (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", name)
	cmd.Env = envWithOptionalGoMod()

	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("go list module dir failed for %s: %w; output: %s", name, err, strings.TrimSpace(string(out)))
	}

	resolvedPath := strings.TrimSpace(string(out))
	if resolvedPath == "" || resolvedPath == "<no value>" {
		return "", fmt.Errorf("go list module dir returned empty path for %s", name)
	}

	return resolvedPath, nil
}

func getGoModFile(path string) (*modfile.File, error) {
	if modPath := os.Getenv(specGoModEnv); modPath != "" {
		if !filepath.IsAbs(modPath) {
			root, err := findModuleRoot(path)
			if err != nil {
				return nil, err
			}
			modPath = filepath.Join(root, modPath)
		}
		buf, err := os.ReadFile(filepath.Clean(modPath))
		if err != nil {
			return nil, errors.New("could not read go.mod")
		}
		return modfile.Parse(modPath, buf, nil)
	}

	root, err := findModuleRoot(path)
	if err != nil {
		return nil, err
	}

	// read go.mod
	buf, err := os.ReadFile(filepath.Join(filepath.Clean(root), "go.mod"))
	if err != nil {
		return nil, errors.New("could not read go.mod")
	}

	// parse go.mod
	return modfile.Parse("go.mod", buf, nil)
}

func findModuleRoot(path string) (string, error) {
	for {
		if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
			return path, nil
		}
		next := filepath.Dir(path)
		if next == path || next == "/" {
			return "", errors.New("could not find go.mod file")
		}
		path = next
	}
}
