// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	phase0 "github.com/attestantio/go-eth2-client/spec/phase0"
	types "github.com/bloxapp/ssv-spec/types"
	beacon "github.com/bloxapp/ssv/protocol/v2/blockchain/beacon"
	validator "github.com/bloxapp/ssv/protocol/v2/ssv/validator"
	types0 "github.com/bloxapp/ssv/protocol/v2/types"
	storage "github.com/bloxapp/ssv/registry/storage"
	basedb "github.com/bloxapp/ssv/storage/basedb"
	common "github.com/ethereum/go-ethereum/common"
	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// ActiveValidatorIndices mocks base method.
func (m *MockController) ActiveValidatorIndices(epoch phase0.Epoch) []phase0.ValidatorIndex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveValidatorIndices", epoch)
	ret0, _ := ret[0].([]phase0.ValidatorIndex)
	return ret0
}

// ActiveValidatorIndices indicates an expected call of ActiveValidatorIndices.
func (mr *MockControllerMockRecorder) ActiveValidatorIndices(epoch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveValidatorIndices", reflect.TypeOf((*MockController)(nil).ActiveValidatorIndices), epoch)
}

// ExecuteDuty mocks base method.
func (m *MockController) ExecuteDuty(logger *zap.Logger, duty *types.Duty) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExecuteDuty", logger, duty)
}

// ExecuteDuty indicates an expected call of ExecuteDuty.
func (mr *MockControllerMockRecorder) ExecuteDuty(logger, duty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDuty", reflect.TypeOf((*MockController)(nil).ExecuteDuty), logger, duty)
}

// GetOperatorData mocks base method.
func (m *MockController) GetOperatorData() *storage.OperatorData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorData")
	ret0, _ := ret[0].(*storage.OperatorData)
	return ret0
}

// GetOperatorData indicates an expected call of GetOperatorData.
func (mr *MockControllerMockRecorder) GetOperatorData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorData", reflect.TypeOf((*MockController)(nil).GetOperatorData))
}

// GetOperatorShares mocks base method.
func (m *MockController) GetOperatorShares() []*types0.SSVShare {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorShares")
	ret0, _ := ret[0].([]*types0.SSVShare)
	return ret0
}

// GetOperatorShares indicates an expected call of GetOperatorShares.
func (mr *MockControllerMockRecorder) GetOperatorShares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorShares", reflect.TypeOf((*MockController)(nil).GetOperatorShares))
}

// GetValidator mocks base method.
func (m *MockController) GetValidator(pubKey string) (*validator.Validator, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidator", pubKey)
	ret0, _ := ret[0].(*validator.Validator)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetValidator indicates an expected call of GetValidator.
func (mr *MockControllerMockRecorder) GetValidator(pubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidator", reflect.TypeOf((*MockController)(nil).GetValidator), pubKey)
}

// GetValidatorStats mocks base method.
func (m *MockController) GetValidatorStats() (uint64, uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorStats")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetValidatorStats indicates an expected call of GetValidatorStats.
func (mr *MockControllerMockRecorder) GetValidatorStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorStats", reflect.TypeOf((*MockController)(nil).GetValidatorStats))
}

// IndicesChangeChan mocks base method.
func (m *MockController) IndicesChangeChan() chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndicesChangeChan")
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

// IndicesChangeChan indicates an expected call of IndicesChangeChan.
func (mr *MockControllerMockRecorder) IndicesChangeChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndicesChangeChan", reflect.TypeOf((*MockController)(nil).IndicesChangeChan))
}

// LiquidateCluster mocks base method.
func (m *MockController) LiquidateCluster(owner common.Address, operatorIDs []uint64, toLiquidate []*types0.SSVShare) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiquidateCluster", owner, operatorIDs, toLiquidate)
	ret0, _ := ret[0].(error)
	return ret0
}

// LiquidateCluster indicates an expected call of LiquidateCluster.
func (mr *MockControllerMockRecorder) LiquidateCluster(owner, operatorIDs, toLiquidate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiquidateCluster", reflect.TypeOf((*MockController)(nil).LiquidateCluster), owner, operatorIDs, toLiquidate)
}

// ReactivateCluster mocks base method.
func (m *MockController) ReactivateCluster(owner common.Address, operatorIDs []uint64, toReactivate []*types0.SSVShare) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReactivateCluster", owner, operatorIDs, toReactivate)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReactivateCluster indicates an expected call of ReactivateCluster.
func (mr *MockControllerMockRecorder) ReactivateCluster(owner, operatorIDs, toReactivate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReactivateCluster", reflect.TypeOf((*MockController)(nil).ReactivateCluster), owner, operatorIDs, toReactivate)
}

// SetOperatorData mocks base method.
func (m *MockController) SetOperatorData(data *storage.OperatorData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOperatorData", data)
}

// SetOperatorData indicates an expected call of SetOperatorData.
func (mr *MockControllerMockRecorder) SetOperatorData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOperatorData", reflect.TypeOf((*MockController)(nil).SetOperatorData), data)
}

// StartNetworkHandlers mocks base method.
func (m *MockController) StartNetworkHandlers() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartNetworkHandlers")
}

// StartNetworkHandlers indicates an expected call of StartNetworkHandlers.
func (mr *MockControllerMockRecorder) StartNetworkHandlers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNetworkHandlers", reflect.TypeOf((*MockController)(nil).StartNetworkHandlers))
}

// StartValidator mocks base method.
func (m *MockController) StartValidator(share *types0.SSVShare) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartValidator", share)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartValidator indicates an expected call of StartValidator.
func (mr *MockControllerMockRecorder) StartValidator(share interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartValidator", reflect.TypeOf((*MockController)(nil).StartValidator), share)
}

// StartValidators mocks base method.
func (m *MockController) StartValidators() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartValidators")
}

// StartValidators indicates an expected call of StartValidators.
func (mr *MockControllerMockRecorder) StartValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartValidators", reflect.TypeOf((*MockController)(nil).StartValidators))
}

// StopValidator mocks base method.
func (m *MockController) StopValidator(publicKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopValidator", publicKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopValidator indicates an expected call of StopValidator.
func (mr *MockControllerMockRecorder) StopValidator(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopValidator", reflect.TypeOf((*MockController)(nil).StopValidator), publicKey)
}

// UpdateFeeRecipient mocks base method.
func (m *MockController) UpdateFeeRecipient(owner, recipient common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeeRecipient", owner, recipient)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeeRecipient indicates an expected call of UpdateFeeRecipient.
func (mr *MockControllerMockRecorder) UpdateFeeRecipient(owner, recipient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeeRecipient", reflect.TypeOf((*MockController)(nil).UpdateFeeRecipient), owner, recipient)
}

// UpdateValidatorMetaDataLoop mocks base method.
func (m *MockController) UpdateValidatorMetaDataLoop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateValidatorMetaDataLoop")
}

// UpdateValidatorMetaDataLoop indicates an expected call of UpdateValidatorMetaDataLoop.
func (mr *MockControllerMockRecorder) UpdateValidatorMetaDataLoop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidatorMetaDataLoop", reflect.TypeOf((*MockController)(nil).UpdateValidatorMetaDataLoop))
}

// MockRecipients is a mock of Recipients interface.
type MockRecipients struct {
	ctrl     *gomock.Controller
	recorder *MockRecipientsMockRecorder
}

// MockRecipientsMockRecorder is the mock recorder for MockRecipients.
type MockRecipientsMockRecorder struct {
	mock *MockRecipients
}

// NewMockRecipients creates a new mock instance.
func NewMockRecipients(ctrl *gomock.Controller) *MockRecipients {
	mock := &MockRecipients{ctrl: ctrl}
	mock.recorder = &MockRecipientsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipients) EXPECT() *MockRecipientsMockRecorder {
	return m.recorder
}

// GetRecipientData mocks base method.
func (m *MockRecipients) GetRecipientData(r basedb.Reader, owner common.Address) (*storage.RecipientData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipientData", r, owner)
	ret0, _ := ret[0].(*storage.RecipientData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRecipientData indicates an expected call of GetRecipientData.
func (mr *MockRecipientsMockRecorder) GetRecipientData(r, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipientData", reflect.TypeOf((*MockRecipients)(nil).GetRecipientData), r, owner)
}

// MockSharesStorage is a mock of SharesStorage interface.
type MockSharesStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSharesStorageMockRecorder
}

// MockSharesStorageMockRecorder is the mock recorder for MockSharesStorage.
type MockSharesStorageMockRecorder struct {
	mock *MockSharesStorage
}

// NewMockSharesStorage creates a new mock instance.
func NewMockSharesStorage(ctrl *gomock.Controller) *MockSharesStorage {
	mock := &MockSharesStorage{ctrl: ctrl}
	mock.recorder = &MockSharesStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharesStorage) EXPECT() *MockSharesStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSharesStorage) Get(txn basedb.Reader, pubKey []byte) *types0.SSVShare {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", txn, pubKey)
	ret0, _ := ret[0].(*types0.SSVShare)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSharesStorageMockRecorder) Get(txn, pubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSharesStorage)(nil).Get), txn, pubKey)
}

// List mocks base method.
func (m *MockSharesStorage) List(txn basedb.Reader, filters ...storage.SharesFilter) []*types0.SSVShare {
	m.ctrl.T.Helper()
	varargs := []interface{}{txn}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*types0.SSVShare)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSharesStorageMockRecorder) List(txn interface{}, filters ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{txn}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSharesStorage)(nil).List), varargs...)
}

// UpdateValidatorMetadata mocks base method.
func (m *MockSharesStorage) UpdateValidatorMetadata(pk string, metadata *beacon.ValidatorMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateValidatorMetadata", pk, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateValidatorMetadata indicates an expected call of UpdateValidatorMetadata.
func (mr *MockSharesStorageMockRecorder) UpdateValidatorMetadata(pk, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidatorMetadata", reflect.TypeOf((*MockSharesStorage)(nil).UpdateValidatorMetadata), pk, metadata)
}

// MockValidatorsMap is a mock of ValidatorsMap interface.
type MockValidatorsMap struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorsMapMockRecorder
}

// MockValidatorsMapMockRecorder is the mock recorder for MockValidatorsMap.
type MockValidatorsMapMockRecorder struct {
	mock *MockValidatorsMap
}

// NewMockValidatorsMap creates a new mock instance.
func NewMockValidatorsMap(ctrl *gomock.Controller) *MockValidatorsMap {
	mock := &MockValidatorsMap{ctrl: ctrl}
	mock.recorder = &MockValidatorsMapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorsMap) EXPECT() *MockValidatorsMapMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockValidatorsMap) Get(txn basedb.Reader, pubKey []byte) *types0.SSVShare {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", txn, pubKey)
	ret0, _ := ret[0].(*types0.SSVShare)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockValidatorsMapMockRecorder) Get(txn, pubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockValidatorsMap)(nil).Get), txn, pubKey)
}

// List mocks base method.
func (m *MockValidatorsMap) List(txn basedb.Reader, filters ...storage.SharesFilter) []*types0.SSVShare {
	m.ctrl.T.Helper()
	varargs := []interface{}{txn}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*types0.SSVShare)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockValidatorsMapMockRecorder) List(txn interface{}, filters ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{txn}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockValidatorsMap)(nil).List), varargs...)
}

// UpdateValidatorMetadata mocks base method.
func (m *MockValidatorsMap) UpdateValidatorMetadata(pk string, metadata *beacon.ValidatorMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateValidatorMetadata", pk, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateValidatorMetadata indicates an expected call of UpdateValidatorMetadata.
func (mr *MockValidatorsMapMockRecorder) UpdateValidatorMetadata(pk, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidatorMetadata", reflect.TypeOf((*MockValidatorsMap)(nil).UpdateValidatorMetadata), pk, metadata)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// ValidatorError mocks base method.
func (m *MockMetrics) ValidatorError(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorError", publicKey)
}

// ValidatorError indicates an expected call of ValidatorError.
func (mr *MockMetricsMockRecorder) ValidatorError(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorError", reflect.TypeOf((*MockMetrics)(nil).ValidatorError), publicKey)
}

// ValidatorExiting mocks base method.
func (m *MockMetrics) ValidatorExiting(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorExiting", publicKey)
}

// ValidatorExiting indicates an expected call of ValidatorExiting.
func (mr *MockMetricsMockRecorder) ValidatorExiting(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorExiting", reflect.TypeOf((*MockMetrics)(nil).ValidatorExiting), publicKey)
}

// ValidatorInactive mocks base method.
func (m *MockMetrics) ValidatorInactive(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorInactive", publicKey)
}

// ValidatorInactive indicates an expected call of ValidatorInactive.
func (mr *MockMetricsMockRecorder) ValidatorInactive(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorInactive", reflect.TypeOf((*MockMetrics)(nil).ValidatorInactive), publicKey)
}

// ValidatorNoIndex mocks base method.
func (m *MockMetrics) ValidatorNoIndex(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorNoIndex", publicKey)
}

// ValidatorNoIndex indicates an expected call of ValidatorNoIndex.
func (mr *MockMetricsMockRecorder) ValidatorNoIndex(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorNoIndex", reflect.TypeOf((*MockMetrics)(nil).ValidatorNoIndex), publicKey)
}

// ValidatorNotActivated mocks base method.
func (m *MockMetrics) ValidatorNotActivated(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorNotActivated", publicKey)
}

// ValidatorNotActivated indicates an expected call of ValidatorNotActivated.
func (mr *MockMetricsMockRecorder) ValidatorNotActivated(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorNotActivated", reflect.TypeOf((*MockMetrics)(nil).ValidatorNotActivated), publicKey)
}

// ValidatorNotFound mocks base method.
func (m *MockMetrics) ValidatorNotFound(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorNotFound", publicKey)
}

// ValidatorNotFound indicates an expected call of ValidatorNotFound.
func (mr *MockMetricsMockRecorder) ValidatorNotFound(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorNotFound", reflect.TypeOf((*MockMetrics)(nil).ValidatorNotFound), publicKey)
}

// ValidatorPending mocks base method.
func (m *MockMetrics) ValidatorPending(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorPending", publicKey)
}

// ValidatorPending indicates an expected call of ValidatorPending.
func (mr *MockMetricsMockRecorder) ValidatorPending(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorPending", reflect.TypeOf((*MockMetrics)(nil).ValidatorPending), publicKey)
}

// ValidatorReady mocks base method.
func (m *MockMetrics) ValidatorReady(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorReady", publicKey)
}

// ValidatorReady indicates an expected call of ValidatorReady.
func (mr *MockMetricsMockRecorder) ValidatorReady(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorReady", reflect.TypeOf((*MockMetrics)(nil).ValidatorReady), publicKey)
}

// ValidatorRemoved mocks base method.
func (m *MockMetrics) ValidatorRemoved(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorRemoved", publicKey)
}

// ValidatorRemoved indicates an expected call of ValidatorRemoved.
func (mr *MockMetricsMockRecorder) ValidatorRemoved(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorRemoved", reflect.TypeOf((*MockMetrics)(nil).ValidatorRemoved), publicKey)
}

// ValidatorSlashed mocks base method.
func (m *MockMetrics) ValidatorSlashed(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorSlashed", publicKey)
}

// ValidatorSlashed indicates an expected call of ValidatorSlashed.
func (mr *MockMetricsMockRecorder) ValidatorSlashed(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorSlashed", reflect.TypeOf((*MockMetrics)(nil).ValidatorSlashed), publicKey)
}

// ValidatorUnknown mocks base method.
func (m *MockMetrics) ValidatorUnknown(publicKey []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidatorUnknown", publicKey)
}

// ValidatorUnknown indicates an expected call of ValidatorUnknown.
func (mr *MockMetricsMockRecorder) ValidatorUnknown(publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorUnknown", reflect.TypeOf((*MockMetrics)(nil).ValidatorUnknown), publicKey)
}
