// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: network_msgs.proto

package network

import (
	proto "github.com/bloxapp/ssv/ibft/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkMsg int32

const (
	// IBFTType are all iBFT related messages
	NetworkMsg_IBFTType NetworkMsg = 0
	// DecidedType is an iBFT specific message for broadcasting post consensus decided message with signatures
	NetworkMsg_DecidedType NetworkMsg = 1
	// SignatureType is an SSV node specific message for broadcasting post consensus signatures on eth2 duties
	NetworkMsg_SignatureType NetworkMsg = 2
	// SyncType is an SSV iBFT specific message that a node uses to sync up with other nodes
	NetworkMsg_SyncType NetworkMsg = 3
	// MpcInitType is an SSV DKG specific message that a node uses to initiate an MPC task
	NetworkMsg_MpcInitType NetworkMsg = 4
	// MpcProtocolType is an SSV DKG specific message that carries the protocol message of an MPC task
	NetworkMsg_MpcProtocolType NetworkMsg = 5
)

// Enum value maps for NetworkMsg.
var (
	NetworkMsg_name = map[int32]string{
		0: "IBFTType",
		1: "DecidedType",
		2: "SignatureType",
		3: "SyncType",
		4: "MpcInitType",
		5: "MpcProtocolType",
	}
	NetworkMsg_value = map[string]int32{
		"IBFTType":        0,
		"DecidedType":     1,
		"SignatureType":   2,
		"SyncType":        3,
		"MpcInitType":     4,
		"MpcProtocolType": 5,
	}
)

func (x NetworkMsg) Enum() *NetworkMsg {
	p := new(NetworkMsg)
	*p = x
	return p
}

func (x NetworkMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_network_msgs_proto_enumTypes[0].Descriptor()
}

func (NetworkMsg) Type() protoreflect.EnumType {
	return &file_network_msgs_proto_enumTypes[0]
}

func (x NetworkMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkMsg.Descriptor instead.
func (NetworkMsg) EnumDescriptor() ([]byte, []int) {
	return file_network_msgs_proto_rawDescGZIP(), []int{0}
}

type Sync int32

const (
	// GetHighestType is a request from peers to return the highest decided/ prepared instance they know of
	Sync_GetHighestType Sync = 0
	// GetInstanceRange is a request from peers to return instances and their decided/ prepared justifications
	Sync_GetInstanceRange Sync = 1
	// GetCurrentInstance is a request from peers to return their current running instance details
	Sync_GetLatestChangeRound Sync = 2
)

// Enum value maps for Sync.
var (
	Sync_name = map[int32]string{
		0: "GetHighestType",
		1: "GetInstanceRange",
		2: "GetLatestChangeRound",
	}
	Sync_value = map[string]int32{
		"GetHighestType":       0,
		"GetInstanceRange":     1,
		"GetLatestChangeRound": 2,
	}
)

func (x Sync) Enum() *Sync {
	p := new(Sync)
	*p = x
	return p
}

func (x Sync) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sync) Descriptor() protoreflect.EnumDescriptor {
	return file_network_msgs_proto_enumTypes[1].Descriptor()
}

func (Sync) Type() protoreflect.EnumType {
	return &file_network_msgs_proto_enumTypes[1]
}

func (x Sync) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sync.Descriptor instead.
func (Sync) EnumDescriptor() ([]byte, []int) {
	return file_network_msgs_proto_rawDescGZIP(), []int{1}
}

type SyncMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignedMessages []*proto.SignedMessage `protobuf:"bytes,1,rep,name=SignedMessages,proto3" json:"SignedMessages,omitempty"`
	FromPeerID     string                 `protobuf:"bytes,2,opt,name=FromPeerID,proto3" json:"FromPeerID,omitempty"`
	Params         []uint64               `protobuf:"varint,3,rep,packed,name=params,proto3" json:"params,omitempty"`
	Lambda         []byte                 `protobuf:"bytes,4,opt,name=Lambda,proto3" json:"Lambda,omitempty"`
	Type           Sync                   `protobuf:"varint,5,opt,name=Type,proto3,enum=network.Sync" json:"Type,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_network_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_network_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetSignedMessages() []*proto.SignedMessage {
	if x != nil {
		return x.SignedMessages
	}
	return nil
}

func (x *SyncMessage) GetFromPeerID() string {
	if x != nil {
		return x.FromPeerID
	}
	return ""
}

func (x *SyncMessage) GetParams() []uint64 {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SyncMessage) GetLambda() []byte {
	if x != nil {
		return x.Lambda
	}
	return nil
}

func (x *SyncMessage) GetType() Sync {
	if x != nil {
		return x.Type
	}
	return Sync_GetHighestType
}

func (x *SyncMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_network_msgs_proto protoreflect.FileDescriptor

var file_network_msgs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x0a, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x53, 0x79,
	0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x6f,
	0x6d, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x4c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x4c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2a, 0x72, 0x0a, 0x0a, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x42, 0x46, 0x54, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x4d, 0x70, 0x63, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x04, 0x12,
	0x13, 0x0a, 0x0f, 0x4d, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x10, 0x05, 0x2a, 0x4a, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02,
	0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_network_msgs_proto_rawDescOnce sync.Once
	file_network_msgs_proto_rawDescData = file_network_msgs_proto_rawDesc
)

func file_network_msgs_proto_rawDescGZIP() []byte {
	file_network_msgs_proto_rawDescOnce.Do(func() {
		file_network_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_msgs_proto_rawDescData)
	})
	return file_network_msgs_proto_rawDescData
}

var file_network_msgs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_network_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_network_msgs_proto_goTypes = []interface{}{
	(NetworkMsg)(0),             // 0: network.NetworkMsg
	(Sync)(0),                   // 1: network.Sync
	(*SyncMessage)(nil),         // 2: network.SyncMessage
	(*proto.SignedMessage)(nil), // 3: proto.SignedMessage
}
var file_network_msgs_proto_depIdxs = []int32{
	3, // 0: network.SyncMessage.SignedMessages:type_name -> proto.SignedMessage
	1, // 1: network.SyncMessage.Type:type_name -> network.Sync
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_network_msgs_proto_init() }
func file_network_msgs_proto_init() {
	if File_network_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_network_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_msgs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_msgs_proto_goTypes,
		DependencyIndexes: file_network_msgs_proto_depIdxs,
		EnumInfos:         file_network_msgs_proto_enumTypes,
		MessageInfos:      file_network_msgs_proto_msgTypes,
	}.Build()
	File_network_msgs_proto = out.File
	file_network_msgs_proto_rawDesc = nil
	file_network_msgs_proto_goTypes = nil
	file_network_msgs_proto_depIdxs = nil
}
