// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network_msgs.proto

package network

import (
	fmt "fmt"
	proto1 "github.com/bloxapp/ssv/ibft/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkMsg int32

const (
	// IBFTType are all iBFT related messages
	NetworkMsg_IBFTType NetworkMsg = 0
	// DecidedType is an iBFT specific message for broadcasting post consensus decided message with signatures
	NetworkMsg_DecidedType NetworkMsg = 1
	// SignatureType is an SSV node specific message for broadcasting post consensus signatures on eth2 duties
	NetworkMsg_SignatureType NetworkMsg = 2
	// SyncType is an SSV iBFT specific message that a node uses to sync up with other nodes
	NetworkMsg_SyncType NetworkMsg = 3
)

var NetworkMsg_name = map[int32]string{
	0: "IBFTType",
	1: "DecidedType",
	2: "SignatureType",
	3: "SyncType",
}

var NetworkMsg_value = map[string]int32{
	"IBFTType":      0,
	"DecidedType":   1,
	"SignatureType": 2,
	"SyncType":      3,
}

func (x NetworkMsg) String() string {
	return proto.EnumName(NetworkMsg_name, int32(x))
}

func (NetworkMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a755f4b722170306, []int{0}
}

type Sync int32

const (
	// GetHighestType is a request from peers to return the highest decided/ prepared instance they know of
	Sync_GetHighestType Sync = 0
	// GetInstanceRange is a request from peers to return instances and their decided/ prepared justifications
	Sync_GetInstanceRange Sync = 1
)

var Sync_name = map[int32]string{
	0: "GetHighestType",
	1: "GetInstanceRange",
}

var Sync_value = map[string]int32{
	"GetHighestType":   0,
	"GetInstanceRange": 1,
}

func (x Sync) String() string {
	return proto.EnumName(Sync_name, int32(x))
}

func (Sync) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a755f4b722170306, []int{1}
}

type SyncMessage struct {
	SignedMessages       []*proto1.SignedMessage `protobuf:"bytes,1,rep,name=SignedMessages,proto3" json:"SignedMessages,omitempty"`
	FromPeerID           string                  `protobuf:"bytes,2,opt,name=FromPeerID,proto3" json:"FromPeerID,omitempty"`
	Params               []uint64                `protobuf:"varint,3,rep,packed,name=params,proto3" json:"params,omitempty"`
	Lambda               []byte                  `protobuf:"bytes,4,opt,name=Lambda,proto3" json:"Lambda,omitempty"`
	Type                 Sync                    `protobuf:"varint,5,opt,name=Type,proto3,enum=network.Sync" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SyncMessage) Reset()         { *m = SyncMessage{} }
func (m *SyncMessage) String() string { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()    {}
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a755f4b722170306, []int{0}
}

func (m *SyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessage.Unmarshal(m, b)
}
func (m *SyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessage.Marshal(b, m, deterministic)
}
func (m *SyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessage.Merge(m, src)
}
func (m *SyncMessage) XXX_Size() int {
	return xxx_messageInfo_SyncMessage.Size(m)
}
func (m *SyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessage proto.InternalMessageInfo

func (m *SyncMessage) GetSignedMessages() []*proto1.SignedMessage {
	if m != nil {
		return m.SignedMessages
	}
	return nil
}

func (m *SyncMessage) GetFromPeerID() string {
	if m != nil {
		return m.FromPeerID
	}
	return ""
}

func (m *SyncMessage) GetParams() []uint64 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SyncMessage) GetLambda() []byte {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *SyncMessage) GetType() Sync {
	if m != nil {
		return m.Type
	}
	return Sync_GetHighestType
}

func init() {
	proto.RegisterEnum("network.NetworkMsg", NetworkMsg_name, NetworkMsg_value)
	proto.RegisterEnum("network.Sync", Sync_name, Sync_value)
	proto.RegisterType((*SyncMessage)(nil), "network.SyncMessage")
}

func init() {
	proto.RegisterFile("network_msgs.proto", fileDescriptor_a755f4b722170306)
}

var fileDescriptor_a755f4b722170306 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0x5a, 0xe7, 0x7c, 0xdd, 0x6a, 0x0d, 0x43, 0x8a, 0x07, 0xa9, 0x9e, 0xca, 0x0e,
	0x55, 0xe6, 0xd5, 0xd3, 0x18, 0x9b, 0x85, 0x4d, 0x24, 0xdb, 0xc9, 0x8b, 0x64, 0xed, 0x23, 0x16,
	0x69, 0x5a, 0x92, 0x88, 0xec, 0x9f, 0xf3, 0x6f, 0x93, 0x74, 0x01, 0x7f, 0x1c, 0x3f, 0x9f, 0xef,
	0xcb, 0xe3, 0x9b, 0x07, 0x54, 0xa2, 0xf9, 0x6c, 0xd4, 0xfb, 0x6b, 0xad, 0x85, 0xce, 0x5a, 0xd5,
	0x98, 0x86, 0x9e, 0x38, 0x77, 0x09, 0x3f, 0xf2, 0xe6, 0x8b, 0x40, 0xb0, 0xd9, 0xcb, 0x62, 0x8d,
	0x5a, 0x73, 0x81, 0xf4, 0x01, 0xc2, 0x4d, 0x25, 0x24, 0x96, 0x4e, 0xe8, 0x98, 0x24, 0x5e, 0x1a,
	0x4c, 0xc7, 0x87, 0xf9, 0xec, 0x4f, 0xc8, 0xfe, 0xcd, 0xd2, 0x2b, 0x80, 0x85, 0x6a, 0xea, 0x67,
	0x44, 0x95, 0xcf, 0xe3, 0x5e, 0x42, 0xd2, 0x53, 0xf6, 0xcb, 0xd0, 0x0b, 0xe8, 0xb7, 0x5c, 0xf1,
	0x5a, 0xc7, 0x5e, 0xe2, 0xa5, 0x3e, 0x73, 0x64, 0xfd, 0x8a, 0xd7, 0xbb, 0x92, 0xc7, 0x7e, 0x42,
	0xd2, 0x21, 0x73, 0x44, 0xaf, 0xc1, 0xdf, 0xee, 0x5b, 0x8c, 0x8f, 0x13, 0x92, 0x86, 0xd3, 0x51,
	0xe6, 0x7e, 0x90, 0xd9, 0xc6, 0xac, 0x8b, 0x26, 0x2b, 0x80, 0xa7, 0x83, 0x5d, 0x6b, 0x41, 0x87,
	0x30, 0xc8, 0x67, 0x8b, 0xad, 0x4d, 0xa2, 0x23, 0x7a, 0x06, 0xc1, 0x1c, 0x8b, 0xaa, 0xc4, 0xb2,
	0x13, 0x84, 0x9e, 0xc3, 0xc8, 0x36, 0xe6, 0xe6, 0x43, 0x61, 0xa7, 0x7a, 0xf6, 0x85, 0xdd, 0xd6,
	0x91, 0x37, 0xb9, 0x03, 0xdf, 0x12, 0xa5, 0x10, 0x2e, 0xd1, 0x3c, 0x56, 0xe2, 0x0d, 0xb5, 0x71,
	0xdb, 0xc6, 0x10, 0x2d, 0xd1, 0xe4, 0x52, 0x1b, 0x2e, 0x0b, 0x64, 0x5c, 0x0a, 0x8c, 0xc8, 0x0c,
	0x5e, 0x06, 0xb7, 0xae, 0xd6, 0xae, 0xdf, 0xdd, 0xe8, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0x1e, 0x61, 0x17, 0x7e, 0x01, 0x00, 0x00,
}
