// Code generated by fastssz. DO NOT EDIT.
// Hash: 4080ac6d77c7ac29416f1dabf14c44f39cc124657e58115d522219c7e27be5f0
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the GloasBeaconVote object
func (g *GloasBeaconVote) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GloasBeaconVote object to a target array
func (g *GloasBeaconVote) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'BlockRoot'
	dst = append(dst, g.BlockRoot[:]...)

	// Field (1) 'Source'
	if g.Source == nil {
		g.Source = new(phase0.Checkpoint)
	}
	if dst, err = g.Source.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Target'
	if g.Target == nil {
		g.Target = new(phase0.Checkpoint)
	}
	if dst, err = g.Target.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'AttestationDataIndex'
	dst = ssz.MarshalUint64(dst, uint64(g.AttestationDataIndex))

	return
}

// UnmarshalSSZ ssz unmarshals the GloasBeaconVote object
func (g *GloasBeaconVote) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 120 {
		return ssz.ErrSize
	}

	// Field (0) 'BlockRoot'
	copy(g.BlockRoot[:], buf[0:32])

	// Field (1) 'Source'
	if g.Source == nil {
		g.Source = new(phase0.Checkpoint)
	}
	if err = g.Source.UnmarshalSSZ(buf[32:72]); err != nil {
		return err
	}

	// Field (2) 'Target'
	if g.Target == nil {
		g.Target = new(phase0.Checkpoint)
	}
	if err = g.Target.UnmarshalSSZ(buf[72:112]); err != nil {
		return err
	}

	// Field (3) 'AttestationDataIndex'
	g.AttestationDataIndex = phase0.CommitteeIndex(ssz.UnmarshallUint64(buf[112:120]))

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GloasBeaconVote object
func (g *GloasBeaconVote) SizeSSZ() (size int) {
	size = 120
	return
}

// HashTreeRoot ssz hashes the GloasBeaconVote object
func (g *GloasBeaconVote) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GloasBeaconVote object with a hasher
func (g *GloasBeaconVote) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'BlockRoot'
	hh.PutBytes(g.BlockRoot[:])

	// Field (1) 'Source'
	if g.Source == nil {
		g.Source = new(phase0.Checkpoint)
	}
	if err = g.Source.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Target'
	if g.Target == nil {
		g.Target = new(phase0.Checkpoint)
	}
	if err = g.Target.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'AttestationDataIndex'
	hh.PutUint64(uint64(g.AttestationDataIndex))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the GloasBeaconVote object
func (g *GloasBeaconVote) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(g)
}
