// Package gloas holds the node-side types for ePBS (EIP-7732 / Gloas), per SIP ssvlabs/SIPs#94.
//
// The Gloas beacon-chain containers — blocks, the execution payload/bid/envelope, payload
// attestations, execution requests, proposer preferences — are go-eth2-client's spec/gloas types,
// aliased in spec_aliases.go rather than hand-rolled, and the §6 blinded envelope — the SSV wire type
// shared with Anchor — is ssv-spec's, aliased alongside them. Defined here are the SSV-protocol
// consensus value (GloasBeaconVote) and the SSV-node types ssv-spec does not carry (builder
// config/entry, the PTC duty, builder request auth, the produceBlockV4 and envelope-publish bodies);
// their SSZ encoders are generated by dynamic-ssz (see generate.go). The associated roles, domains, message types, and partial-signature types live
// in ssv-spec (spectypes).
package gloas
