// Package gloas holds the node-side types for ePBS (EIP-7732 / Gloas), per SIP ssvlabs/SIPs#94.
//
// The Gloas beacon-chain containers — blocks, the execution payload/bid/envelope, payload
// attestations, execution requests, proposer preferences — are go-eth2-client's spec/gloas types,
// aliased in spec_aliases.go rather than hand-rolled, and the SSV wire types shared with Anchor — the
// §2 consensus value (GloasBeaconVote) and the §6 blinded envelope — are ssv-spec's, aliased alongside
// them. Defined here are the §4 consensus value (GloasProposalData) and the SSV-node types (builder
// config/entry, the PTC duty, builder request auth, the produceBlockV4 and envelope-publish bodies);
// their SSZ encoders are generated by dynamic-ssz (see generate.go). The associated roles, domains,
// message types, and partial-signature types live in ssv-spec (spectypes).
package gloas
