// Package gloas holds the node-side types for ePBS (EIP-7732 / Gloas), per SIP ssvlabs/SIPs#94.
//
// The Gloas beacon-chain containers — blocks, the execution payload/bid/envelope, payload
// attestations, execution requests, proposer preferences — are go-eth2-client's spec/gloas types,
// aliased in spec_aliases.go rather than hand-rolled. Defined here are the SSV-protocol consensus
// values (GloasBeaconVote, the EnvelopeConsensusData QBFT wrapper, the blinded envelope) and the
// SSV-node types ssv-spec does not carry (builder config/entry, the PTC duty, builder request auth);
// their SSZ encoders are generated by dynamic-ssz (see generate.go). The associated roles, domains,
// and partial-signature types live in ssv-spec (spectypes).
package gloas
