// Code generated by fastssz. DO NOT EDIT.
// Hash: 2584b9344ef92a617476649180e7fbe0ce01af59f5f5ee00dbbc4c36c057d595
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the EnvelopeConsensusData object
func (e *EnvelopeConsensusData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the EnvelopeConsensusData object to a target array
func (e *EnvelopeConsensusData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Offset (0) 'Duty'
	dst = ssz.WriteOffset(dst, offset)
	offset += e.Duty.SizeSSZ()

	// Field (1) 'Version'
	dst = ssz.MarshalUint64(dst, uint64(e.Version))

	// Offset (2) 'DataSSZ'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Duty'
	if dst, err = e.Duty.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'DataSSZ'
	if size := len(e.DataSSZ); size > 8388608 {
		err = ssz.ErrBytesLengthFn("EnvelopeConsensusData.DataSSZ", size, 8388608)
		return
	}
	dst = append(dst, e.DataSSZ...)

	return
}

// UnmarshalSSZ ssz unmarshals the EnvelopeConsensusData object
func (e *EnvelopeConsensusData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2 uint64

	// Offset (0) 'Duty'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Version'
	e.Version = spec.DataVersion(ssz.UnmarshallUint64(buf[4:12]))

	// Offset (2) 'DataSSZ'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (0) 'Duty'
	{
		buf = tail[o0:o2]
		if err = e.Duty.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'DataSSZ'
	{
		buf = tail[o2:]
		if len(buf) > 8388608 {
			return ssz.ErrBytesLength
		}
		if cap(e.DataSSZ) == 0 {
			e.DataSSZ = make([]byte, 0, len(buf))
		}
		e.DataSSZ = append(e.DataSSZ, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the EnvelopeConsensusData object
func (e *EnvelopeConsensusData) SizeSSZ() (size int) {
	size = 16

	// Field (0) 'Duty'
	size += e.Duty.SizeSSZ()

	// Field (2) 'DataSSZ'
	size += len(e.DataSSZ)

	return
}

// HashTreeRoot ssz hashes the EnvelopeConsensusData object
func (e *EnvelopeConsensusData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the EnvelopeConsensusData object with a hasher
func (e *EnvelopeConsensusData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Duty'
	if err = e.Duty.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Version'
	hh.PutUint64(uint64(e.Version))

	// Field (2) 'DataSSZ'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(e.DataSSZ))
		if byteLen > 8388608 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(e.DataSSZ)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (8388608+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the EnvelopeConsensusData object
func (e *EnvelopeConsensusData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(e)
}
