// Code generated by fastssz. DO NOT EDIT.
// Hash: 96ab5c5b5fa31abaf95dfca1088f2821793e0442ab69d4fef607a3c534b58289
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadBid object to a target array
func (e *ExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(224)

	// Field (0) 'ParentBlockHash'
	dst = append(dst, e.ParentBlockHash[:]...)

	// Field (1) 'ParentBlockRoot'
	dst = append(dst, e.ParentBlockRoot[:]...)

	// Field (2) 'BlockHash'
	dst = append(dst, e.BlockHash[:]...)

	// Field (3) 'PrevRandao'
	dst = append(dst, e.PrevRandao[:]...)

	// Field (4) 'FeeRecipient'
	dst = append(dst, e.FeeRecipient[:]...)

	// Field (5) 'GasLimit'
	dst = ssz.MarshalUint64(dst, e.GasLimit)

	// Field (6) 'BuilderIndex'
	dst = ssz.MarshalUint64(dst, uint64(e.BuilderIndex))

	// Field (7) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(e.Slot))

	// Field (8) 'Value'
	dst = ssz.MarshalUint64(dst, uint64(e.Value))

	// Field (9) 'ExecutionPayment'
	dst = ssz.MarshalUint64(dst, uint64(e.ExecutionPayment))

	// Offset (10) 'BlobKZGCommitments'
	dst = ssz.WriteOffset(dst, offset)

	// Field (11) 'ExecutionRequestsRoot'
	dst = append(dst, e.ExecutionRequestsRoot[:]...)

	// Field (10) 'BlobKZGCommitments'
	if size := len(e.BlobKZGCommitments); size > 4096 {
		err = ssz.ErrListTooBigFn("ExecutionPayloadBid.BlobKZGCommitments", size, 4096)
		return
	}
	for ii := 0; ii < len(e.BlobKZGCommitments); ii++ {
		dst = append(dst, e.BlobKZGCommitments[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 224 {
		return ssz.ErrSize
	}

	tail := buf
	var o10 uint64

	// Field (0) 'ParentBlockHash'
	copy(e.ParentBlockHash[:], buf[0:32])

	// Field (1) 'ParentBlockRoot'
	copy(e.ParentBlockRoot[:], buf[32:64])

	// Field (2) 'BlockHash'
	copy(e.BlockHash[:], buf[64:96])

	// Field (3) 'PrevRandao'
	copy(e.PrevRandao[:], buf[96:128])

	// Field (4) 'FeeRecipient'
	copy(e.FeeRecipient[:], buf[128:148])

	// Field (5) 'GasLimit'
	e.GasLimit = ssz.UnmarshallUint64(buf[148:156])

	// Field (6) 'BuilderIndex'
	e.BuilderIndex = BuilderIndex(ssz.UnmarshallUint64(buf[156:164]))

	// Field (7) 'Slot'
	e.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[164:172]))

	// Field (8) 'Value'
	e.Value = phase0.Gwei(ssz.UnmarshallUint64(buf[172:180]))

	// Field (9) 'ExecutionPayment'
	e.ExecutionPayment = phase0.Gwei(ssz.UnmarshallUint64(buf[180:188]))

	// Offset (10) 'BlobKZGCommitments'
	if o10 = ssz.ReadOffset(buf[188:192]); o10 > size {
		return ssz.ErrOffset
	}

	if o10 != 224 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (11) 'ExecutionRequestsRoot'
	copy(e.ExecutionRequestsRoot[:], buf[192:224])

	// Field (10) 'BlobKZGCommitments'
	{
		buf = tail[o10:]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		e.BlobKZGCommitments = make([]deneb.KZGCommitment, num)
		for ii := 0; ii < num; ii++ {
			copy(e.BlobKZGCommitments[ii][:], buf[ii*48:(ii+1)*48])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) SizeSSZ() (size int) {
	size = 224

	// Field (10) 'BlobKZGCommitments'
	size += len(e.BlobKZGCommitments) * 48

	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadBid object with a hasher
func (e *ExecutionPayloadBid) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ParentBlockHash'
	hh.PutBytes(e.ParentBlockHash[:])

	// Field (1) 'ParentBlockRoot'
	hh.PutBytes(e.ParentBlockRoot[:])

	// Field (2) 'BlockHash'
	hh.PutBytes(e.BlockHash[:])

	// Field (3) 'PrevRandao'
	hh.PutBytes(e.PrevRandao[:])

	// Field (4) 'FeeRecipient'
	hh.PutBytes(e.FeeRecipient[:])

	// Field (5) 'GasLimit'
	hh.PutUint64(e.GasLimit)

	// Field (6) 'BuilderIndex'
	hh.PutUint64(uint64(e.BuilderIndex))

	// Field (7) 'Slot'
	hh.PutUint64(uint64(e.Slot))

	// Field (8) 'Value'
	hh.PutUint64(uint64(e.Value))

	// Field (9) 'ExecutionPayment'
	hh.PutUint64(uint64(e.ExecutionPayment))

	// Field (10) 'BlobKZGCommitments'
	{
		if size := len(e.BlobKZGCommitments); size > 4096 {
			err = ssz.ErrListTooBigFn("ExecutionPayloadBid.BlobKZGCommitments", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range e.BlobKZGCommitments {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(e.BlobKZGCommitments))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (11) 'ExecutionRequestsRoot'
	hh.PutBytes(e.ExecutionRequestsRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(e)
}

// MarshalSSZ ssz marshals the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedExecutionPayloadBid object to a target array
func (s *SignedExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[4:100])

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(ExecutionPayloadBid)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ExecutionPayloadBid)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedExecutionPayloadBid object with a hasher
func (s *SignedExecutionPayloadBid) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
