package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
)

// BlindedExecutionPayloadEnvelope is the blinded form of the Gloas ExecutionPayloadEnvelope that the §6
// envelope-signing duty signs (SIP #94 §6): the full `payload` is replaced by
// PayloadRoot = hash_tree_root(payload). By progressive-container merkleization its hash-tree root
// equals the full envelope's, so a BLS signature over the blinded signing root is valid for the full
// SignedExecutionPayloadEnvelope. It rides in EnvelopeConsensusData.DataSSZ; blinding keeps that QBFT
// value bounded — a few hundred bytes rather than the full payload's hundreds of KB to ~MB.
//
// It is an SSV-internal consensus type only, never sent on the wire: beacon-APIs#624 removed the
// identically named spec container, and §6 publishes the full SignedExecutionPayloadEnvelope. The full
// envelope, its Signed wrapper, and the ExecutionRequests it references are go-eth2-client spec/gloas
// types (see spec_aliases.go); the ExecutionRequests list is the EIP-8282 five-list variant, not
// electra's three. Encoders are generated by pk910/dynamic-ssz (see generate.go).
type BlindedExecutionPayloadEnvelope struct {
	PayloadRoot           phase0.Root        `ssz-index:"0" ssz-size:"32"`
	ExecutionRequests     *ExecutionRequests `ssz-index:"1"`
	BuilderIndex          BuilderIndex       `ssz-index:"2"`
	BeaconBlockRoot       phase0.Root        `ssz-index:"3" ssz-size:"32"`
	ParentBeaconBlockRoot phase0.Root        `ssz-index:"4" ssz-size:"32"`
}

// Encode/Decode wrap SSZ (de)serialization — the form carried in the §6 QBFT consensus DataSSZ.
func (b *BlindedExecutionPayloadEnvelope) Encode() ([]byte, error)  { return b.MarshalSSZ() }
func (b *BlindedExecutionPayloadEnvelope) Decode(data []byte) error { return b.UnmarshalSSZ(data) }
