// Code generated by fastssz. DO NOT EDIT.
// Hash: d998a7b21a5ca8a83f980a2b202c32bad3a5fb6b7a089127fb17f94628fe5954
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the ProposerPreferences object
func (p *ProposerPreferences) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the ProposerPreferences object to a target array
func (p *ProposerPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'DependentRoot'
	dst = append(dst, p.DependentRoot[:]...)

	// Field (1) 'ProposalSlot'
	dst = ssz.MarshalUint64(dst, uint64(p.ProposalSlot))

	// Field (2) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, uint64(p.ValidatorIndex))

	// Field (3) 'FeeRecipient'
	dst = append(dst, p.FeeRecipient[:]...)

	// Field (4) 'TargetGasLimit'
	dst = ssz.MarshalUint64(dst, p.TargetGasLimit)

	return
}

// UnmarshalSSZ ssz unmarshals the ProposerPreferences object
func (p *ProposerPreferences) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 76 {
		return ssz.ErrSize
	}

	// Field (0) 'DependentRoot'
	copy(p.DependentRoot[:], buf[0:32])

	// Field (1) 'ProposalSlot'
	p.ProposalSlot = phase0.Slot(ssz.UnmarshallUint64(buf[32:40]))

	// Field (2) 'ValidatorIndex'
	p.ValidatorIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[40:48]))

	// Field (3) 'FeeRecipient'
	copy(p.FeeRecipient[:], buf[48:68])

	// Field (4) 'TargetGasLimit'
	p.TargetGasLimit = ssz.UnmarshallUint64(buf[68:76])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ProposerPreferences object
func (p *ProposerPreferences) SizeSSZ() (size int) {
	size = 76
	return
}

// HashTreeRoot ssz hashes the ProposerPreferences object
func (p *ProposerPreferences) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the ProposerPreferences object with a hasher
func (p *ProposerPreferences) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'DependentRoot'
	hh.PutBytes(p.DependentRoot[:])

	// Field (1) 'ProposalSlot'
	hh.PutUint64(uint64(p.ProposalSlot))

	// Field (2) 'ValidatorIndex'
	hh.PutUint64(uint64(p.ValidatorIndex))

	// Field (3) 'FeeRecipient'
	hh.PutBytes(p.FeeRecipient[:])

	// Field (4) 'TargetGasLimit'
	hh.PutUint64(p.TargetGasLimit)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ProposerPreferences object
func (p *ProposerPreferences) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(p)
}

// MarshalSSZ ssz marshals the SignedProposerPreferences object
func (s *SignedProposerPreferences) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedProposerPreferences object to a target array
func (s *SignedProposerPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ProposerPreferences)
	}
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedProposerPreferences object
func (s *SignedProposerPreferences) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 172 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ProposerPreferences)
	}
	if err = s.Message.UnmarshalSSZ(buf[0:76]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[76:172])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedProposerPreferences object
func (s *SignedProposerPreferences) SizeSSZ() (size int) {
	size = 172
	return
}

// HashTreeRoot ssz hashes the SignedProposerPreferences object
func (s *SignedProposerPreferences) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedProposerPreferences object with a hasher
func (s *SignedProposerPreferences) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ProposerPreferences)
	}
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedProposerPreferences object
func (s *SignedProposerPreferences) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
