// Code generated by MockGen. DO NOT EDIT.
// Source: ./storage.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=./mocks/storage.go -source=./storage.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	big "math/big"
	reflect "reflect"

	bellatrix "github.com/attestantio/go-eth2-client/spec/bellatrix"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ssvlabs/ssv-spec/types"
	storage "github.com/ssvlabs/ssv/operator/storage"
	storage0 "github.com/ssvlabs/ssv/registry/storage"
	basedb "github.com/ssvlabs/ssv/storage/basedb"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockStorage) Begin() basedb.Txn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(basedb.Txn)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockStorageMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockStorage)(nil).Begin))
}

// BeginRead mocks base method.
func (m *MockStorage) BeginRead() basedb.ReadTxn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRead")
	ret0, _ := ret[0].(basedb.ReadTxn)
	return ret0
}

// BeginRead indicates an expected call of BeginRead.
func (mr *MockStorageMockRecorder) BeginRead() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRead", reflect.TypeOf((*MockStorage)(nil).BeginRead))
}

// BumpNonce mocks base method.
func (m *MockStorage) BumpNonce(rw basedb.ReadWriter, owner common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpNonce", rw, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpNonce indicates an expected call of BumpNonce.
func (mr *MockStorageMockRecorder) BumpNonce(rw, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpNonce", reflect.TypeOf((*MockStorage)(nil).BumpNonce), rw, owner)
}

// DeleteConfig mocks base method.
func (m *MockStorage) DeleteConfig(rw basedb.ReadWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", rw)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockStorageMockRecorder) DeleteConfig(rw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockStorage)(nil).DeleteConfig), rw)
}

// DeleteOperatorData mocks base method.
func (m *MockStorage) DeleteOperatorData(rw basedb.ReadWriter, id types.OperatorID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperatorData", rw, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOperatorData indicates an expected call of DeleteOperatorData.
func (mr *MockStorageMockRecorder) DeleteOperatorData(rw, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperatorData", reflect.TypeOf((*MockStorage)(nil).DeleteOperatorData), rw, id)
}

// DeleteRecipientData mocks base method.
func (m *MockStorage) DeleteRecipientData(rw basedb.ReadWriter, owner common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipientData", rw, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipientData indicates an expected call of DeleteRecipientData.
func (mr *MockStorageMockRecorder) DeleteRecipientData(rw, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipientData", reflect.TypeOf((*MockStorage)(nil).DeleteRecipientData), rw, owner)
}

// DropOperators mocks base method.
func (m *MockStorage) DropOperators() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropOperators")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropOperators indicates an expected call of DropOperators.
func (mr *MockStorageMockRecorder) DropOperators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropOperators", reflect.TypeOf((*MockStorage)(nil).DropOperators))
}

// DropRecipients mocks base method.
func (m *MockStorage) DropRecipients() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropRecipients")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropRecipients indicates an expected call of DropRecipients.
func (mr *MockStorageMockRecorder) DropRecipients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropRecipients", reflect.TypeOf((*MockStorage)(nil).DropRecipients))
}

// DropRegistryData mocks base method.
func (m *MockStorage) DropRegistryData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropRegistryData")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropRegistryData indicates an expected call of DropRegistryData.
func (mr *MockStorageMockRecorder) DropRegistryData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropRegistryData", reflect.TypeOf((*MockStorage)(nil).DropRegistryData))
}

// GetConfig mocks base method.
func (m *MockStorage) GetConfig(rw basedb.ReadWriter) (*storage.ConfigLock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", rw)
	ret0, _ := ret[0].(*storage.ConfigLock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockStorageMockRecorder) GetConfig(rw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockStorage)(nil).GetConfig), rw)
}

// GetLastProcessedBlock mocks base method.
func (m *MockStorage) GetLastProcessedBlock(r basedb.Reader) (*big.Int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastProcessedBlock", r)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastProcessedBlock indicates an expected call of GetLastProcessedBlock.
func (mr *MockStorageMockRecorder) GetLastProcessedBlock(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastProcessedBlock", reflect.TypeOf((*MockStorage)(nil).GetLastProcessedBlock), r)
}

// GetNextNonce mocks base method.
func (m *MockStorage) GetNextNonce(r basedb.Reader, owner common.Address) (storage0.Nonce, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextNonce", r, owner)
	ret0, _ := ret[0].(storage0.Nonce)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextNonce indicates an expected call of GetNextNonce.
func (mr *MockStorageMockRecorder) GetNextNonce(r, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextNonce", reflect.TypeOf((*MockStorage)(nil).GetNextNonce), r, owner)
}

// GetOperatorData mocks base method.
func (m *MockStorage) GetOperatorData(r basedb.Reader, id types.OperatorID) (*storage0.OperatorData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorData", r, id)
	ret0, _ := ret[0].(*storage0.OperatorData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOperatorData indicates an expected call of GetOperatorData.
func (mr *MockStorageMockRecorder) GetOperatorData(r, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorData", reflect.TypeOf((*MockStorage)(nil).GetOperatorData), r, id)
}

// GetOperatorDataByPubKey mocks base method.
func (m *MockStorage) GetOperatorDataByPubKey(r basedb.Reader, operatorPubKey []byte) (*storage0.OperatorData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorDataByPubKey", r, operatorPubKey)
	ret0, _ := ret[0].(*storage0.OperatorData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOperatorDataByPubKey indicates an expected call of GetOperatorDataByPubKey.
func (mr *MockStorageMockRecorder) GetOperatorDataByPubKey(r, operatorPubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorDataByPubKey", reflect.TypeOf((*MockStorage)(nil).GetOperatorDataByPubKey), r, operatorPubKey)
}

// GetOperatorsPrefix mocks base method.
func (m *MockStorage) GetOperatorsPrefix() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorsPrefix")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetOperatorsPrefix indicates an expected call of GetOperatorsPrefix.
func (mr *MockStorageMockRecorder) GetOperatorsPrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorsPrefix", reflect.TypeOf((*MockStorage)(nil).GetOperatorsPrefix))
}

// GetPrivateKeyHash mocks base method.
func (m *MockStorage) GetPrivateKeyHash() (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKeyHash")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPrivateKeyHash indicates an expected call of GetPrivateKeyHash.
func (mr *MockStorageMockRecorder) GetPrivateKeyHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKeyHash", reflect.TypeOf((*MockStorage)(nil).GetPrivateKeyHash))
}

// GetRecipientData mocks base method.
func (m *MockStorage) GetRecipientData(r basedb.Reader, owner common.Address) (*storage0.RecipientData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipientData", r, owner)
	ret0, _ := ret[0].(*storage0.RecipientData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRecipientData indicates an expected call of GetRecipientData.
func (mr *MockStorageMockRecorder) GetRecipientData(r, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipientData", reflect.TypeOf((*MockStorage)(nil).GetRecipientData), r, owner)
}

// GetRecipientDataMany mocks base method.
func (m *MockStorage) GetRecipientDataMany(r basedb.Reader, owners []common.Address) (map[common.Address]bellatrix.ExecutionAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipientDataMany", r, owners)
	ret0, _ := ret[0].(map[common.Address]bellatrix.ExecutionAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipientDataMany indicates an expected call of GetRecipientDataMany.
func (mr *MockStorageMockRecorder) GetRecipientDataMany(r, owners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipientDataMany", reflect.TypeOf((*MockStorage)(nil).GetRecipientDataMany), r, owners)
}

// GetRecipientsPrefix mocks base method.
func (m *MockStorage) GetRecipientsPrefix() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipientsPrefix")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetRecipientsPrefix indicates an expected call of GetRecipientsPrefix.
func (mr *MockStorageMockRecorder) GetRecipientsPrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipientsPrefix", reflect.TypeOf((*MockStorage)(nil).GetRecipientsPrefix))
}

// ListOperators mocks base method.
func (m *MockStorage) ListOperators(r basedb.Reader, from, to uint64) ([]storage0.OperatorData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperators", r, from, to)
	ret0, _ := ret[0].([]storage0.OperatorData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOperators indicates an expected call of ListOperators.
func (mr *MockStorageMockRecorder) ListOperators(r, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperators", reflect.TypeOf((*MockStorage)(nil).ListOperators), r, from, to)
}

// OperatorsExist mocks base method.
func (m *MockStorage) OperatorsExist(r basedb.Reader, ids []types.OperatorID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OperatorsExist", r, ids)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperatorsExist indicates an expected call of OperatorsExist.
func (mr *MockStorageMockRecorder) OperatorsExist(r, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperatorsExist", reflect.TypeOf((*MockStorage)(nil).OperatorsExist), r, ids)
}

// SaveConfig mocks base method.
func (m *MockStorage) SaveConfig(rw basedb.ReadWriter, config *storage.ConfigLock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConfig", rw, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConfig indicates an expected call of SaveConfig.
func (mr *MockStorageMockRecorder) SaveConfig(rw, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConfig", reflect.TypeOf((*MockStorage)(nil).SaveConfig), rw, config)
}

// SaveLastProcessedBlock mocks base method.
func (m *MockStorage) SaveLastProcessedBlock(rw basedb.ReadWriter, offset *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLastProcessedBlock", rw, offset)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLastProcessedBlock indicates an expected call of SaveLastProcessedBlock.
func (mr *MockStorageMockRecorder) SaveLastProcessedBlock(rw, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLastProcessedBlock", reflect.TypeOf((*MockStorage)(nil).SaveLastProcessedBlock), rw, offset)
}

// SaveOperatorData mocks base method.
func (m *MockStorage) SaveOperatorData(rw basedb.ReadWriter, operatorData *storage0.OperatorData) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOperatorData", rw, operatorData)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOperatorData indicates an expected call of SaveOperatorData.
func (mr *MockStorageMockRecorder) SaveOperatorData(rw, operatorData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOperatorData", reflect.TypeOf((*MockStorage)(nil).SaveOperatorData), rw, operatorData)
}

// SavePrivateKeyHash mocks base method.
func (m *MockStorage) SavePrivateKeyHash(privKeyHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateKeyHash", privKeyHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateKeyHash indicates an expected call of SavePrivateKeyHash.
func (mr *MockStorageMockRecorder) SavePrivateKeyHash(privKeyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateKeyHash", reflect.TypeOf((*MockStorage)(nil).SavePrivateKeyHash), privKeyHash)
}

// SaveRecipientData mocks base method.
func (m *MockStorage) SaveRecipientData(rw basedb.ReadWriter, recipientData *storage0.RecipientData) (*storage0.RecipientData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecipientData", rw, recipientData)
	ret0, _ := ret[0].(*storage0.RecipientData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRecipientData indicates an expected call of SaveRecipientData.
func (mr *MockStorageMockRecorder) SaveRecipientData(rw, recipientData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecipientData", reflect.TypeOf((*MockStorage)(nil).SaveRecipientData), rw, recipientData)
}

// Shares mocks base method.
func (m *MockStorage) Shares() storage0.Shares {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shares")
	ret0, _ := ret[0].(storage0.Shares)
	return ret0
}

// Shares indicates an expected call of Shares.
func (mr *MockStorageMockRecorder) Shares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shares", reflect.TypeOf((*MockStorage)(nil).Shares))
}

// ValidatorStore mocks base method.
func (m *MockStorage) ValidatorStore() storage0.ValidatorStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorStore")
	ret0, _ := ret[0].(storage0.ValidatorStore)
	return ret0
}

// ValidatorStore indicates an expected call of ValidatorStore.
func (mr *MockStorageMockRecorder) ValidatorStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorStore", reflect.TypeOf((*MockStorage)(nil).ValidatorStore))
}
