// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgs.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoundState int32

const (
	RoundState_Preprepare  RoundState = 0
	RoundState_Prepare     RoundState = 1
	RoundState_Commit      RoundState = 2
	RoundState_ChangeRound RoundState = 3
	RoundState_Decide      RoundState = 4
)

var RoundState_name = map[int32]string{
	0: "Preprepare",
	1: "Prepare",
	2: "Commit",
	3: "ChangeRound",
	4: "Decide",
}

var RoundState_value = map[string]int32{
	"Preprepare":  0,
	"Prepare":     1,
	"Commit":      2,
	"ChangeRound": 3,
	"Decide":      4,
}

func (x RoundState) String() string {
	return proto.EnumName(RoundState_name, int32(x))
}

func (RoundState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_952909143bb80d72, []int{0}
}

type Message struct {
	Type                 RoundState `protobuf:"varint,1,opt,name=type,proto3,enum=ibft.v1alpha.RoundState" json:"type,omitempty"`
	Round                uint64     `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Lambda               []byte     `protobuf:"bytes,3,opt,name=lambda,proto3" json:"lambda,omitempty"`
	Value                []byte     `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_952909143bb80d72, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() RoundState {
	if m != nil {
		return m.Type
	}
	return RoundState_Preprepare
}

func (m *Message) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Message) GetLambda() []byte {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SignedMessage struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	IbftId               uint64   `protobuf:"varint,3,opt,name=ibft_id,json=ibftId,proto3" json:"ibft_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_952909143bb80d72, []int{1}
}

func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetIbftId() uint64 {
	if m != nil {
		return m.IbftId
	}
	return 0
}

type ChangeRoundData struct {
	PreparedRound        uint64   `protobuf:"varint,1,opt,name=prepared_round,json=preparedRound,proto3" json:"prepared_round,omitempty"`
	PreparedValue        []byte   `protobuf:"bytes,2,opt,name=prepared_value,json=preparedValue,proto3" json:"prepared_value,omitempty"`
	JustificationMsg     *Message `protobuf:"bytes,3,opt,name=justification_msg,json=justificationMsg,proto3" json:"justification_msg,omitempty"`
	JustificationSig     []byte   `protobuf:"bytes,4,opt,name=justification_sig,json=justificationSig,proto3" json:"justification_sig,omitempty"`
	SignedIds            []uint64 `protobuf:"varint,5,rep,packed,name=signed_ids,json=signedIds,proto3" json:"signed_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRoundData) Reset()         { *m = ChangeRoundData{} }
func (m *ChangeRoundData) String() string { return proto.CompactTextString(m) }
func (*ChangeRoundData) ProtoMessage()    {}
func (*ChangeRoundData) Descriptor() ([]byte, []int) {
	return fileDescriptor_952909143bb80d72, []int{2}
}

func (m *ChangeRoundData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoundData.Unmarshal(m, b)
}
func (m *ChangeRoundData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoundData.Marshal(b, m, deterministic)
}
func (m *ChangeRoundData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoundData.Merge(m, src)
}
func (m *ChangeRoundData) XXX_Size() int {
	return xxx_messageInfo_ChangeRoundData.Size(m)
}
func (m *ChangeRoundData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoundData.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoundData proto.InternalMessageInfo

func (m *ChangeRoundData) GetPreparedRound() uint64 {
	if m != nil {
		return m.PreparedRound
	}
	return 0
}

func (m *ChangeRoundData) GetPreparedValue() []byte {
	if m != nil {
		return m.PreparedValue
	}
	return nil
}

func (m *ChangeRoundData) GetJustificationMsg() *Message {
	if m != nil {
		return m.JustificationMsg
	}
	return nil
}

func (m *ChangeRoundData) GetJustificationSig() []byte {
	if m != nil {
		return m.JustificationSig
	}
	return nil
}

func (m *ChangeRoundData) GetSignedIds() []uint64 {
	if m != nil {
		return m.SignedIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("ibft.v1alpha.RoundState", RoundState_name, RoundState_value)
	proto.RegisterType((*Message)(nil), "ibft.v1alpha.Message")
	proto.RegisterType((*SignedMessage)(nil), "ibft.v1alpha.SignedMessage")
	proto.RegisterType((*ChangeRoundData)(nil), "ibft.v1alpha.ChangeRoundData")
}

func init() {
	proto.RegisterFile("msgs.proto", fileDescriptor_952909143bb80d72)
}

var fileDescriptor_952909143bb80d72 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xda, 0xac, 0x15, 0xb7, 0x5d, 0x17, 0x2c, 0x3e, 0x22, 0x04, 0xa2, 0x14, 0x21, 0x55,
	0x7c, 0x24, 0xda, 0x10, 0x7f, 0x60, 0xdb, 0x03, 0x7b, 0x98, 0x34, 0xb9, 0x12, 0x0f, 0xbc, 0x44,
	0x4e, 0xed, 0xba, 0x46, 0x49, 0x1c, 0xc5, 0x4e, 0x05, 0x42, 0x3c, 0xf0, 0xef, 0xf8, 0x15, 0xfc,
	0x16, 0xe4, 0xeb, 0x94, 0x65, 0x08, 0x69, 0x6f, 0x3e, 0xf7, 0x9e, 0x7b, 0x73, 0xce, 0xc9, 0x05,
	0x28, 0x8d, 0x34, 0x49, 0xdd, 0x68, 0xab, 0xc9, 0x54, 0xe5, 0x1b, 0x9b, 0xec, 0x4e, 0x58, 0x51,
	0x6f, 0xd9, 0x93, 0x77, 0x52, 0xd9, 0x6d, 0x9b, 0x27, 0x6b, 0x5d, 0xa6, 0x52, 0x4b, 0x9d, 0x22,
	0x29, 0x6f, 0x37, 0x88, 0x10, 0xe0, 0xcb, 0x0f, 0x2f, 0xbe, 0xc3, 0xf8, 0x4a, 0x18, 0xc3, 0xa4,
	0x20, 0x6f, 0x21, 0xb4, 0xdf, 0x6a, 0x11, 0x07, 0xf3, 0x60, 0x39, 0x3b, 0x8d, 0x93, 0xfe, 0xda,
	0x84, 0xea, 0xb6, 0xe2, 0x2b, 0xcb, 0xac, 0xa0, 0xc8, 0x22, 0x0f, 0xe0, 0xb0, 0x71, 0xb5, 0x78,
	0x30, 0x0f, 0x96, 0x21, 0xf5, 0x80, 0x3c, 0x82, 0x51, 0xc1, 0xca, 0x9c, 0xb3, 0x78, 0x38, 0x0f,
	0x96, 0x53, 0xda, 0x21, 0xc7, 0xde, 0xb1, 0xa2, 0x15, 0x71, 0x88, 0x65, 0x0f, 0x16, 0x3f, 0xe0,
	0x68, 0xa5, 0x64, 0x25, 0xf8, 0x5e, 0xc2, 0x07, 0x18, 0x97, 0xfe, 0x89, 0x2a, 0x26, 0xa7, 0x0f,
	0x6f, 0xab, 0xe8, 0x78, 0x67, 0xe1, 0xaf, 0xdf, 0xcf, 0x0f, 0xe8, 0x9e, 0x4b, 0x9e, 0xc2, 0x3d,
	0xa3, 0x64, 0xc5, 0x6c, 0xdb, 0x08, 0xd4, 0x33, 0xa5, 0x37, 0x05, 0xf2, 0x18, 0xc6, 0x6e, 0x49,
	0xa6, 0x38, 0x8a, 0x0a, 0xe9, 0xc8, 0xc1, 0x4b, 0xbe, 0xf8, 0x39, 0x80, 0xe3, 0xf3, 0x2d, 0xab,
	0xa4, 0x40, 0x77, 0x17, 0xcc, 0x32, 0xf2, 0x0a, 0x66, 0x75, 0x23, 0x6a, 0xd6, 0x08, 0x9e, 0x79,
	0x7f, 0x01, 0xce, 0x1c, 0xed, 0xab, 0x48, 0x25, 0x6f, 0x7a, 0x34, 0x6f, 0x0c, 0x3f, 0xdb, 0x09,
	0xfb, 0x4b, 0xfe, 0xe4, 0x5a, 0xe4, 0x23, 0xdc, 0xff, 0xd2, 0x1a, 0xab, 0x36, 0x6a, 0xcd, 0xac,
	0xd2, 0x55, 0x56, 0x1a, 0x89, 0x52, 0xee, 0xf0, 0x17, 0xdd, 0x9a, 0xba, 0x32, 0x92, 0x9c, 0xfc,
	0xbb, 0xc9, 0x28, 0xe9, 0x23, 0xfd, 0xef, 0xc8, 0x4a, 0x49, 0xf2, 0x0c, 0xc0, 0x60, 0xc6, 0x99,
	0xe2, 0x26, 0x3e, 0x9c, 0x0f, 0x97, 0xa1, 0x0f, 0x47, 0xf0, 0x4b, 0x6e, 0x5e, 0x53, 0x80, 0x9b,
	0x5f, 0x4b, 0x66, 0x00, 0xd7, 0x8d, 0xe8, 0xd4, 0x47, 0x07, 0x64, 0x02, 0xe3, 0xeb, 0x0e, 0x04,
	0x04, 0x60, 0x74, 0xae, 0xcb, 0x52, 0xd9, 0x68, 0x40, 0x8e, 0x61, 0xd2, 0x4b, 0x2e, 0x1a, 0xba,
	0xe6, 0x85, 0x58, 0x2b, 0x2e, 0xa2, 0xf0, 0xec, 0xe5, 0xe7, 0x17, 0xbd, 0x23, 0xcc, 0x0b, 0xfd,
	0x95, 0xd5, 0x75, 0x6a, 0xcc, 0x2e, 0x75, 0x66, 0x53, 0x77, 0x3e, 0x26, 0x1f, 0xe1, 0xfd, 0xbd,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x80, 0xfe, 0x3d, 0xc8, 0xca, 0x02, 0x00, 0x00,
}
