#!/bin/bash

# Extract the Git tag from the SOURCE_COMMIT
APP_VERSION=$(git describe --tags "${SOURCE_COMMIT}")

# Pass the Git tag as a build argument
docker build --build-arg APP_VERSION="${APP_VERSION}" -t "${IMAGE_NAME}" .
