---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-full-node-mainnet-1-api
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ssv-full-node-mainnet-1.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ssv-full-node-mainnet-1-api
  http:
  - route:
    - destination:
        host: ssv-full-node-mainnet-1
        port:
          number: 16015
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-full-node-mainnet-1-api
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ssv-full-node-mainnet-1.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-full-node-mainnet-1
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ws-ssv-full-node-mainnet-1.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ssv-full-node-mainnet-1
  http:
  - route:
    - destination:
        host: ssv-full-node-mainnet-1
        port:
          number: 14015
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-full-node-mainnet-1
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ws-ssv-full-node-mainnet-1.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-full-node-mainnet-1
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-full-node-mainnet-1
spec:
  type: ClusterIP
  ports:
    - port: 12015
      protocol: UDP
      targetPort: 12015
      name: port-12015
    - port: 13015
      protocol: TCP
      targetPort: 13015
      name: port-13015
    - port: 14015
      protocol: TCP
      targetPort: 14015
      name: port-14015
    - port: 15015
      protocol: TCP
      targetPort: 15015
      name: port-15015
    - port: 16015
      protocol: TCP
      targetPort: 16015
      name: port-16015
  selector:
    app: ssv-full-node-mainnet-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-full-node-mainnet-1
  name: ssv-full-node-mainnet-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-full-node-mainnet-1
  template:
    metadata:
      labels:
        app: ssv-full-node-mainnet-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-exporter
      containers:
      - name: ssv-full-node-mainnet-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_EXPORTER_CPU_LIMIT
            memory: REPLACE_EXPORTER_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12015
          name: port-12015
          hostPort: 12015
          protocol: UDP
        - containerPort: 13015
          name: port-13015
          hostPort: 13015
        - containerPort: 14015
          name: port-14015
          hostPort: 14015
        - containerPort: 15015
          name: port-15015
          hostPort: 15015
        - containerPort: 16015
          name: port-16015
          hostPort: 16015
        env:
          - name: SHARE_CONFIG
            value: "./data/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "mainnet"
          - name: DB_PATH
            value: "./data/db-mainnet"
          - name: METRICS_API_PORT
            value: "15015"
          - name: SSV_API_PORT
            value: "16015"
          - name: ENABLE_PROFILE
            value: "true"
          - name: UDP_PORT
            value: "12015"
          - name: TCP_PORT
            value: "13015"
          - name: WS_API_PORT
            value: "14015"
          - name: FULLNODE
            value: "true"
          - name: EXPORTER
            value: "true"
          - name: MSG_WORKERS_COUNT
            value: "1024"
          - name: MSG_WORKER_BUFFER_SIZE
            value: "2048"
          - name: SUBNETS
            value: "0xffffffffffffffffffffffffffffffff"
          - name: P2P_MAX_PEERS
            value: "300"
        volumeMounts:
        - mountPath: /data
          name: ssv-full-node-mainnet-1
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-full-node-mainnet-1-cm
      volumes:
      - name: ssv-full-node-mainnet-1
        persistentVolumeClaim:
          claimName: ssv-full-node-mainnet-1
      - name: ssv-full-node-mainnet-1-cm
        configMap:
          name: ssv-full-node-mainnet-1-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
