---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-full-node-mainnet-2
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ws-ssv-full-node-mainnet-2.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ssv-full-node-mainnet-2
  http:
  - route:
    - destination:
        host: ssv-full-node-mainnet-2
        port:
          number: 14016
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-full-node-mainnet-2
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ws-ssv-full-node-mainnet-2.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-full-node-mainnet-2
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-full-node-mainnet-2
spec:
  type: ClusterIP
  ports:
    - port: 12016
      protocol: UDP
      targetPort: 12016
      name: port-12016
    - port: 13016
      protocol: TCP
      targetPort: 13016
      name: port-13016
    - port: 14016
      protocol: TCP
      targetPort: 14016
      name: port-14016
    - port: 15016
      protocol: TCP
      targetPort: 15016
      name: port-15016
    - port: 16016
      protocol: TCP
      targetPort: 16016
      name: port-16016
  selector:
    app: ssv-full-node-mainnet-2
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-full-node-mainnet-2
  name: ssv-full-node-mainnet-2
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-full-node-mainnet-2
  template:
    metadata:
      labels:
        app: ssv-full-node-mainnet-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-full-node-mainnet-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_EXPORTER_CPU_LIMIT
            memory: REPLACE_EXPORTER_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12016
          name: port-12016
          hostPort: 12016
          protocol: UDP
        - containerPort: 13016
          name: port-13016
          hostPort: 13016
        - containerPort: 14016
          name: port-14016
          hostPort: 14016
        - containerPort: 15016
          name: port-15016
          hostPort: 15016
        - containerPort: 16016
          name: port-16016
          hostPort: 16016
        env:
          - name: SHARE_CONFIG
            value: "/data/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "mainnet"
          - name: DB_PATH
            value: "/data/db-mainnet"
          - name: METRICS_API_PORT
            value: "15016"
          - name: SSV_API_PORT
            value: "16016"
          - name: ENABLE_PROFILE
            value: "true"
          - name: UDP_PORT
            value: "12016"
          - name: TCP_PORT
            value: "13016"
          - name: WS_API_PORT
            value: "14016"
          - name: FULLNODE
            value: "true"
          - name: EXPORTER
            value: "true"
          - name: MSG_WORKERS_COUNT
            value: "1024"
          - name: MSG_WORKER_BUFFER_SIZE
            value: "2048"
          - name: SUBNETS
            value: "0xffffffffffffffffffffffffffffffff"
          - name: P2P_MAX_PEERS
            value: "300"
        volumeMounts:
        - mountPath: /data
          name: ssv-full-node-mainnet-2
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-full-node-mainnet-2-cm
      volumes:
      - name: ssv-full-node-mainnet-2
        persistentVolumeClaim:
          claimName: ssv-full-node-mainnet-2
      - name: ssv-full-node-mainnet-2-cm
        configMap:
          name: ssv-full-node-mainnet-2-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
