---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-holesky-1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-holesky-1
spec:
  type: ClusterIP
  ports:
    - port: 12022
      protocol: UDP
      targetPort: 12022
      name: port-12022
    - port: 13022
      protocol: TCP
      targetPort: 13022
      name: port-13022
    - port: 15022
      protocol: TCP
      targetPort: 15022
      name: port-15022
    - port: 16022
      protocol: TCP
      targetPort: 16022
      name: port-16022
  selector:
    app: ssv-node-holesky-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-holesky-1
  name: ssv-node-holesky-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-holesky-1
  template:
    metadata:
      labels:
        app: ssv-node-holesky-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-holesky-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12022
          name: port-12022
          hostPort: 12022
          protocol: UDP
        - containerPort: 13022
          name: port-13022
          hostPort: 13022
        - containerPort: 15022
          name: port-15022
          hostPort: 15022
        - containerPort: 16022
          name: port-16022
          hostPort: 16022
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: DB_PATH
            value: ./data/db-holesky
          - name: NETWORK
            value: holesky
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: METRICS_API_PORT
            value: "15022"
          - name: SSV_API_PORT
            value: "16022"
          - name: ENABLE_PROFILE
            value: "true"
          - name: BUILDER_PROPOSALS
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-holesky-1
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-holesky-1-cm
      volumes:
      - name: ssv-node-holesky-1
        persistentVolumeClaim:
          claimName: ssv-node-holesky-1
      - name: ssv-node-holesky-1-cm
        configMap:
          name: ssv-node-holesky-1-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
