// Code generated by MockGen. DO NOT EDIT.
// Source: ./network.go
//
// Generated by this command:
//
//	mockgen -package=networkconfig -destination=./network_mock.go -source=./network.go
//

// Package networkconfig is a generated GoMock package.
package networkconfig

import (
	big "math/big"
	reflect "reflect"
	time "time"

	spec "github.com/attestantio/go-eth2-client/spec"
	phase0 "github.com/attestantio/go-eth2-client/spec/phase0"
	types "github.com/ssvlabs/ssv-spec/types"
	gomock "go.uber.org/mock/gomock"
)

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
	isgomock struct{}
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// DomainType mocks base method.
func (m *MockNetwork) DomainType() types.DomainType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DomainType")
	ret0, _ := ret[0].(types.DomainType)
	return ret0
}

// DomainType indicates an expected call of DomainType.
func (mr *MockNetworkMockRecorder) DomainType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DomainType", reflect.TypeOf((*MockNetwork)(nil).DomainType))
}

// EpochDuration mocks base method.
func (m *MockNetwork) EpochDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// EpochDuration indicates an expected call of EpochDuration.
func (mr *MockNetworkMockRecorder) EpochDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochDuration", reflect.TypeOf((*MockNetwork)(nil).EpochDuration))
}

// EpochFirstSlot mocks base method.
func (m *MockNetwork) EpochFirstSlot(epoch phase0.Epoch) phase0.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochFirstSlot", epoch)
	ret0, _ := ret[0].(phase0.Slot)
	return ret0
}

// EpochFirstSlot indicates an expected call of EpochFirstSlot.
func (mr *MockNetworkMockRecorder) EpochFirstSlot(epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochFirstSlot", reflect.TypeOf((*MockNetwork)(nil).EpochFirstSlot), epoch)
}

// EpochStartTime mocks base method.
func (m *MockNetwork) EpochStartTime(epoch phase0.Epoch) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochStartTime", epoch)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// EpochStartTime indicates an expected call of EpochStartTime.
func (mr *MockNetworkMockRecorder) EpochStartTime(epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochStartTime", reflect.TypeOf((*MockNetwork)(nil).EpochStartTime), epoch)
}

// EpochsPerSyncCommitteePeriod mocks base method.
func (m *MockNetwork) EpochsPerSyncCommitteePeriod() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochsPerSyncCommitteePeriod")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// EpochsPerSyncCommitteePeriod indicates an expected call of EpochsPerSyncCommitteePeriod.
func (mr *MockNetworkMockRecorder) EpochsPerSyncCommitteePeriod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochsPerSyncCommitteePeriod", reflect.TypeOf((*MockNetwork)(nil).EpochsPerSyncCommitteePeriod))
}

// EstimatedCurrentEpoch mocks base method.
func (m *MockNetwork) EstimatedCurrentEpoch() phase0.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedCurrentEpoch")
	ret0, _ := ret[0].(phase0.Epoch)
	return ret0
}

// EstimatedCurrentEpoch indicates an expected call of EstimatedCurrentEpoch.
func (mr *MockNetworkMockRecorder) EstimatedCurrentEpoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedCurrentEpoch", reflect.TypeOf((*MockNetwork)(nil).EstimatedCurrentEpoch))
}

// EstimatedCurrentSlot mocks base method.
func (m *MockNetwork) EstimatedCurrentSlot() phase0.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedCurrentSlot")
	ret0, _ := ret[0].(phase0.Slot)
	return ret0
}

// EstimatedCurrentSlot indicates an expected call of EstimatedCurrentSlot.
func (mr *MockNetworkMockRecorder) EstimatedCurrentSlot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedCurrentSlot", reflect.TypeOf((*MockNetwork)(nil).EstimatedCurrentSlot))
}

// EstimatedEpochAtSlot mocks base method.
func (m *MockNetwork) EstimatedEpochAtSlot(slot phase0.Slot) phase0.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedEpochAtSlot", slot)
	ret0, _ := ret[0].(phase0.Epoch)
	return ret0
}

// EstimatedEpochAtSlot indicates an expected call of EstimatedEpochAtSlot.
func (mr *MockNetworkMockRecorder) EstimatedEpochAtSlot(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedEpochAtSlot", reflect.TypeOf((*MockNetwork)(nil).EstimatedEpochAtSlot), slot)
}

// EstimatedSlotAtTime mocks base method.
func (m *MockNetwork) EstimatedSlotAtTime(arg0 time.Time) phase0.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedSlotAtTime", arg0)
	ret0, _ := ret[0].(phase0.Slot)
	return ret0
}

// EstimatedSlotAtTime indicates an expected call of EstimatedSlotAtTime.
func (mr *MockNetworkMockRecorder) EstimatedSlotAtTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedSlotAtTime", reflect.TypeOf((*MockNetwork)(nil).EstimatedSlotAtTime), arg0)
}

// EstimatedSyncCommitteePeriodAtEpoch mocks base method.
func (m *MockNetwork) EstimatedSyncCommitteePeriodAtEpoch(epoch phase0.Epoch) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedSyncCommitteePeriodAtEpoch", epoch)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// EstimatedSyncCommitteePeriodAtEpoch indicates an expected call of EstimatedSyncCommitteePeriodAtEpoch.
func (mr *MockNetworkMockRecorder) EstimatedSyncCommitteePeriodAtEpoch(epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedSyncCommitteePeriodAtEpoch", reflect.TypeOf((*MockNetwork)(nil).EstimatedSyncCommitteePeriodAtEpoch), epoch)
}

// EstimatedTimeAtSlot mocks base method.
func (m *MockNetwork) EstimatedTimeAtSlot(slot phase0.Slot) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedTimeAtSlot", slot)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// EstimatedTimeAtSlot indicates an expected call of EstimatedTimeAtSlot.
func (mr *MockNetworkMockRecorder) EstimatedTimeAtSlot(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedTimeAtSlot", reflect.TypeOf((*MockNetwork)(nil).EstimatedTimeAtSlot), slot)
}

// FirstEpochOfSyncPeriod mocks base method.
func (m *MockNetwork) FirstEpochOfSyncPeriod(period uint64) phase0.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstEpochOfSyncPeriod", period)
	ret0, _ := ret[0].(phase0.Epoch)
	return ret0
}

// FirstEpochOfSyncPeriod indicates an expected call of FirstEpochOfSyncPeriod.
func (mr *MockNetworkMockRecorder) FirstEpochOfSyncPeriod(period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstEpochOfSyncPeriod", reflect.TypeOf((*MockNetwork)(nil).FirstEpochOfSyncPeriod), period)
}

// FirstSlotAtEpoch mocks base method.
func (m *MockNetwork) FirstSlotAtEpoch(epoch phase0.Epoch) phase0.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstSlotAtEpoch", epoch)
	ret0, _ := ret[0].(phase0.Slot)
	return ret0
}

// FirstSlotAtEpoch indicates an expected call of FirstSlotAtEpoch.
func (mr *MockNetworkMockRecorder) FirstSlotAtEpoch(epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstSlotAtEpoch", reflect.TypeOf((*MockNetwork)(nil).FirstSlotAtEpoch), epoch)
}

// ForkAtEpoch mocks base method.
func (m *MockNetwork) ForkAtEpoch(epoch phase0.Epoch) (spec.DataVersion, phase0.Fork) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkAtEpoch", epoch)
	ret0, _ := ret[0].(spec.DataVersion)
	ret1, _ := ret[1].(phase0.Fork)
	return ret0, ret1
}

// ForkAtEpoch indicates an expected call of ForkAtEpoch.
func (mr *MockNetworkMockRecorder) ForkAtEpoch(epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkAtEpoch", reflect.TypeOf((*MockNetwork)(nil).ForkAtEpoch), epoch)
}

// GasLimit36Epoch mocks base method.
func (m *MockNetwork) GasLimit36Epoch() phase0.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasLimit36Epoch")
	ret0, _ := ret[0].(phase0.Epoch)
	return ret0
}

// GasLimit36Epoch indicates an expected call of GasLimit36Epoch.
func (mr *MockNetworkMockRecorder) GasLimit36Epoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasLimit36Epoch", reflect.TypeOf((*MockNetwork)(nil).GasLimit36Epoch))
}

// GenesisTime mocks base method.
func (m *MockNetwork) GenesisTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenesisTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GenesisTime indicates an expected call of GenesisTime.
func (mr *MockNetworkMockRecorder) GenesisTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenesisTime", reflect.TypeOf((*MockNetwork)(nil).GenesisTime))
}

// GenesisValidatorsRoot mocks base method.
func (m *MockNetwork) GenesisValidatorsRoot() phase0.Root {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenesisValidatorsRoot")
	ret0, _ := ret[0].(phase0.Root)
	return ret0
}

// GenesisValidatorsRoot indicates an expected call of GenesisValidatorsRoot.
func (mr *MockNetworkMockRecorder) GenesisValidatorsRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenesisValidatorsRoot", reflect.TypeOf((*MockNetwork)(nil).GenesisValidatorsRoot))
}

// IntervalDuration mocks base method.
func (m *MockNetwork) IntervalDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntervalDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// IntervalDuration indicates an expected call of IntervalDuration.
func (mr *MockNetworkMockRecorder) IntervalDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntervalDuration", reflect.TypeOf((*MockNetwork)(nil).IntervalDuration))
}

// IsFirstSlotOfEpoch mocks base method.
func (m *MockNetwork) IsFirstSlotOfEpoch(slot phase0.Slot) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFirstSlotOfEpoch", slot)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFirstSlotOfEpoch indicates an expected call of IsFirstSlotOfEpoch.
func (mr *MockNetworkMockRecorder) IsFirstSlotOfEpoch(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFirstSlotOfEpoch", reflect.TypeOf((*MockNetwork)(nil).IsFirstSlotOfEpoch), slot)
}

// LastSlotOfSyncPeriod mocks base method.
func (m *MockNetwork) LastSlotOfSyncPeriod(period uint64) phase0.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSlotOfSyncPeriod", period)
	ret0, _ := ret[0].(phase0.Slot)
	return ret0
}

// LastSlotOfSyncPeriod indicates an expected call of LastSlotOfSyncPeriod.
func (mr *MockNetworkMockRecorder) LastSlotOfSyncPeriod(period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSlotOfSyncPeriod", reflect.TypeOf((*MockNetwork)(nil).LastSlotOfSyncPeriod), period)
}

// NetworkName mocks base method.
func (m *MockNetwork) NetworkName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkName")
	ret0, _ := ret[0].(string)
	return ret0
}

// NetworkName indicates an expected call of NetworkName.
func (mr *MockNetworkMockRecorder) NetworkName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkName", reflect.TypeOf((*MockNetwork)(nil).NetworkName))
}

// RegistrySyncOffset mocks base method.
func (m *MockNetwork) RegistrySyncOffset() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrySyncOffset")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// RegistrySyncOffset indicates an expected call of RegistrySyncOffset.
func (mr *MockNetworkMockRecorder) RegistrySyncOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrySyncOffset", reflect.TypeOf((*MockNetwork)(nil).RegistrySyncOffset))
}

// SlotDuration mocks base method.
func (m *MockNetwork) SlotDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// SlotDuration indicates an expected call of SlotDuration.
func (mr *MockNetworkMockRecorder) SlotDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotDuration", reflect.TypeOf((*MockNetwork)(nil).SlotDuration))
}

// SlotEndTime mocks base method.
func (m *MockNetwork) SlotEndTime(slot phase0.Slot) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotEndTime", slot)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// SlotEndTime indicates an expected call of SlotEndTime.
func (mr *MockNetworkMockRecorder) SlotEndTime(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotEndTime", reflect.TypeOf((*MockNetwork)(nil).SlotEndTime), slot)
}

// SlotStartTime mocks base method.
func (m *MockNetwork) SlotStartTime(slot phase0.Slot) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotStartTime", slot)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// SlotStartTime indicates an expected call of SlotStartTime.
func (mr *MockNetworkMockRecorder) SlotStartTime(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotStartTime", reflect.TypeOf((*MockNetwork)(nil).SlotStartTime), slot)
}

// SlotsPerEpoch mocks base method.
func (m *MockNetwork) SlotsPerEpoch() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotsPerEpoch")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// SlotsPerEpoch indicates an expected call of SlotsPerEpoch.
func (mr *MockNetworkMockRecorder) SlotsPerEpoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotsPerEpoch", reflect.TypeOf((*MockNetwork)(nil).SlotsPerEpoch))
}

// SyncCommitteeSize mocks base method.
func (m *MockNetwork) SyncCommitteeSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncCommitteeSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// SyncCommitteeSize indicates an expected call of SyncCommitteeSize.
func (mr *MockNetworkMockRecorder) SyncCommitteeSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCommitteeSize", reflect.TypeOf((*MockNetwork)(nil).SyncCommitteeSize))
}

// TotalEthereumValidators mocks base method.
func (m *MockNetwork) TotalEthereumValidators() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalEthereumValidators")
	ret0, _ := ret[0].(int)
	return ret0
}

// TotalEthereumValidators indicates an expected call of TotalEthereumValidators.
func (mr *MockNetworkMockRecorder) TotalEthereumValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalEthereumValidators", reflect.TypeOf((*MockNetwork)(nil).TotalEthereumValidators))
}
