---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-full-node-prater-2
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ws-ssv-full-node-prater-2.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ssv-full-node-prater-2
  http:
  - route:
    - destination:
        host: ssv-full-node-prater-2
        port:
          number: 14010
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-full-node-prater-2
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ws-ssv-full-node-prater-2.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-full-node-prater-2
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-full-node-prater-2
spec:
  type: ClusterIP
  ports:
    - port: 12010
      protocol: UDP
      targetPort: 12010
      name: port-12010
    - port: 13010
      protocol: TCP
      targetPort: 13010
      name: port-13010
    - port: 14010
      protocol: TCP
      targetPort: 14010
      name: port-14010
    - port: 15010
      protocol: TCP
      targetPort: 15010
      name: port-15010
    - port: 16010
      protocol: TCP
      targetPort: 16010
      name: port-16010
  selector:
    app: ssv-full-node-prater-2
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-full-node-prater-2
  name: ssv-full-node-prater-2
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-full-node-prater-2
  template:
    metadata:
      labels:
        app: ssv-full-node-prater-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-full-node-prater-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_EXPORTER_CPU_LIMIT
            memory: REPLACE_EXPORTER_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12010
          name: port-12010
          hostPort: 12010
          protocol: UDP
        - containerPort: 13010
          name: port-13010
          hostPort: 13010
        - containerPort: 14010
          name: port-14010
          hostPort: 14010
        - containerPort: 15010
          name: port-15010
          hostPort: 15010
        - containerPort: 16010
          name: port-16010
          hostPort: 16010
        env:
          - name: SHARE_CONFIG
            value: "/data/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "jato-v2"
          - name: DB_PATH
            value: "/data/db-jato-v2"
          - name: METRICS_API_PORT
            value: "15010"
          - name: SSV_API_PORT
            value: "16010"
          - name: ENABLE_PROFILE
            value: "true"
          - name: UDP_PORT
            value: "12010"
          - name: TCP_PORT
            value: "13010"
          - name: WS_API_PORT
            value: "14010"
          - name: FULLNODE
            value: "true"
          - name: EXPORTER
            value: "true"
          - name: MSG_WORKERS_COUNT
            value: "1024"
          - name: MSG_WORKER_BUFFER_SIZE
            value: "2048"
          - name: SUBNETS
            value: "0xffffffffffffffffffffffffffffffff"
          - name: P2P_MAX_PEERS
            value: "300"
        volumeMounts:
        - mountPath: /data
          name: ssv-full-node-prater-2
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-full-node-prater-2-cm
      volumes:
      - name: ssv-full-node-prater-2
        persistentVolumeClaim:
          claimName: ssv-full-node-prater-2
      - name: ssv-full-node-prater-2-cm
        configMap:
          name: ssv-full-node-prater-2-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
