name: Run dutytracer collector benchmark
run-name: ${{ github.actor }} started workflow 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - feat/exporter-v2

jobs:
  Test-with-LFS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true # Ensure Git LFS files are fetched

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Run benchmark
        id: bench
        run: |
          go test -benchmem -run=^$ -bench ^BenchmarkTracer$ github.com/ssvlabs/ssv/exporter/dutytracer -v

      - name: Run eviction test
        id: eviction
        run: |
          go test -tags lfs -timeout 5s -run ^TestEviction$ github.com/ssvlabs/ssv/exporter/dutytracer -v

      - run: echo "🍏 This job's status is ${{ job.status }}."
