name: All tests

on:
#  push:
#    branches:
#      - "main"
#  #      - 'stage'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            ssvsigner/go.sum

      - name: Full-test
        run: make full-test
