name: Spec tests

on:
  push:
    branches:
      - stage
      - main
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.24.x"

      - name: Run spec tests
        run: make spec-test
        timeout-minutes: 80
