name: Spec Alignment

on:
  workflow_dispatch:

jobs:
  align:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            scripts/differ/go.sum

      - name: Tidy up dependencies
        run: go mod tidy

      - name: Install Differ
        run: cd ./scripts/differ && go install .

      - name: Run Differ
        run: cd ./scripts/spec-alignment && ./differ.sh

      - name: Upload output.diff
        if: failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: output.diff
          path: ./scripts/spec-alignment/output.diff
