name: SSV-Signer E2E tests

on:
  push:
    branches:
      - stage
      - main
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ssvsigner/go.mod
          cache: true
          cache-dependency-path: ssvsigner/go.sum

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build ssv-signer image (cached)
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ssvsigner/Dockerfile
          tags: ssv-signer:latest
          load: true
          cache-from: type=gha,scope=ssvsigner-e2e
          cache-to: type=gha,mode=max,scope=ssvsigner-e2e

      - name: Run SSV-Signer E2E tests
        run: |
          cd ssvsigner
          make test-e2e-no-build
