name: Unit tests


on:
  push:
    branches:
      - stage
      - main
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            ssvsigner/go.sum

      - name: Run unit tests
        run: make unit-test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: core
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ssvsigner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum
            ssvsigner/go.sum

      - name: Run ssvsigner unit tests
        run: make ssvsigner-test

      - name: Upload ssvsigner coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./ssvsigner/coverage.out
          flags: ssvsigner
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
